### ISSUE TITLE
windows 11

### ISSUE THREAD

**Issue by Steelduck1** [LordOfMice/hidusbf#100]
![screenshot 1](https://user-images.githubusercontent.com/93537840/139698386-326a7414-3b6f-4d5f-ad75-7d3cd771946b.png)
getting this error since windows 11.

**Comment by LordOfMice** [comment]
Nothing is changed from Windows 10. Read readme.

**Comment by Alegzandr** [comment]
> Nothing is changed from Windows 10. Read readme.

Windows 11 forces Secure Boot, so it doesn't work

**Comment by LordOfMice** [comment]
1. "Windows 11 without TPM and Secure Boot"
2.  >or modify the Registry accordingly
This is probably working too.

**Comment by Alegzandr** [comment]
> 1. "Windows 11 without TPM and Secure Boot"
> 2. > or modify the Registry accordingly
> 
> This is probably working too.

Some games required Secure Boot on Windows 11 in order to work, Valorant for example

**Comment by LordOfMice** [comment]
Before answering second time try to ask yourself "am i understand all previous information?".
