### ISSUE TITLE
it works for a few seconds...

### ISSUE THREAD

**Issue by SKYROX0OFF** [LordOfMice/hidusbf#104]
is it normal that it only works for 10-15 seconds?  when I do "restart" my input lag decreases but after 10-15 seconds I feel it increases, I use a scuf "scuf impact" controller

**Comment by LordOfMice** [comment]
>is it normal that it only works for 10-15 seconds?

No. Such behavior is highly unlikely. But this is overclocking, it can be unsuccessful.

>I feel 

"feel" is bad term here. "measure" is good.
