### ISSUE TITLE
error message when I try to put my controller to 1 bIntervale

### ISSUE THREAD

**Issue by UnderFoxBH** [LordOfMice/hidusbf#105]
Hi , I tried to put my controller who is basically at 6 bIntervale to 1 but when I do I get an error message. If possible , I would like to get some help.
![bandicam 2021-11-26 20-53-43-229](https://user-images.githubusercontent.com/95102965/143625312-e75bec58-8f32-4053-8d15-108c4595e608.jpg)

**Comment by LordOfMice** [comment]
I think you have to read something before asking. readme or pinned issues, i assume.
