### ISSUE TITLE
Error 577 on "filter on device" - secure boot issue

### ISSUE THREAD

**Issue by 4PERTURE** [LordOfMice/hidusbf#107]
hi, ive seen another issue with this problem and i have followed the solution, the program works with secure boot off, but for some reason bluetooth on this laptop only works when secure boot is on. i need this driver to underclock my mouse cause my laptop cant handle it, lags games. is there a way to fix/workaround this issue without disabling secure boot

**Comment by LordOfMice** [comment]
i think you have to read pinned issue about your problem before making another one
