### ISSUE TITLE
controller underclock problem

### ISSUE THREAD

**Issue by Kuudooo** [LordOfMice/hidusbf#109]
Hello, I have a problem underclocking my controller. It is impossible for me to reset the basic polling rate of my controller. On the software he tells me that I have given it back to the base but unfortunately in game, it is still oc.
Even when I plug my controller into a port that I do not have OC, its polling rate is 1000 hertz, even when I am in bluetooth my controller is OC.
The problem is very mystical.

I have already re-installed the ports, re-installed windows, but the oc is still there

**Comment by LordOfMice** [comment]
This is not this software related problem (but you can use this software for underclocking too, of course).
