### ISSUE TITLE
Restart Function

### ISSUE THREAD

**Issue by moheat** [LordOfMice/hidusbf#11]
I haven't been able to use the Restart Device function since a few days. I suspect it's because of the new windows update because I reset my computer without installing anything else (an anti-virus or otherwise) and the error still shows up. 
![image](https://user-images.githubusercontent.com/69147577/89175173-d1d56f00-d5a4-11ea-9333-bbd679ab7511.png)

**Comment by LordOfMice** [comment]
Try to run SX64.EXE directly (as Admin, of cause) and check errors. 
And you can use 100% working workaround described in readme - detach and attach device or reboot.

**Comment by LordOfMice** [comment]
Try to run SX64.EXE directly (as Admin, of cause) and check errors. 
And you can use 100% working workaround described in readme - detach and attach device or reboot.

**Comment by AimforWC** [comment]
Hey LordofMice my overclocking is very laggy and i turned secure boot off and it still feels laggy. I really need help.

**Comment by LordOfMice** [comment]
>overclocking is very laggy
because it is overclocking, isn't it? this is device dependent whether you get something useful or no.
