### ISSUE TITLE
Bitlocker Recovery key code

### ISSUE THREAD

**Issue by aiyad11** [LordOfMice/hidusbf#118]
Hey there, I tried to disable the secure boot but I got stuck in the recovery key part I didn't know how to get it, any other solutions?.

**Comment by aiyad11** [comment]
Hi, bro I read what you said and I tried my best but I didn't know how to do it can you help us please.

**Comment by LordOfMice** [comment]
No, you didn't. Ask the RIGHT question.

**Comment by aiyad11** [comment]
I really need help because I didn't know how to do it can you send us a link or a video to watch how to do and apply the steps.

**Comment by LordOfMice** [comment]
Once again, until you using words "it","what","this" I continue to think that you didn't read readme because there is not SUCH words. There is some other, EXACT words describing what you have to do. Ask me WHAT you need to do (but don't know how) and I will answer.
