### ISSUE TITLE
USB Port Broken?

### ISSUE THREAD

**Issue by NobleCC** [LordOfMice/hidusbf#119]
I recently overclocked my new controller (Razer wolverine) and it happen to not work this time for some reason while I have done this multiple time before I never had this issue and need help fixing. Basically I did all step to overclocked but on the last where I needed to added the fliters message pop up about secure boots etc but I pay not attention to it and suddenly my controller turn off and I unplug it and back on it still not working then I unplug through USB port but then I noticed it bricked my port while I connected to other port it work just fine, I already did full clean pc reset yet the issue still not fixed. Never heard of this issue before and think Im only one that having this problem and if anyone know how to fixed it I appreciated it because it is an expensive latest motherboard I got gotten recently.

**Comment by LordOfMice** [comment]
just read readme
