### ISSUE TITLE
Issues around non signed driver with DS4 controller

### ISSUE THREAD

**Issue by l3vines** [LordOfMice/hidusbf#12]
Hi, i would love to use your setup but the issue with it is that it will only work if i disable secure boot/driver signature enforcement or test mode.

I'm debating if i should do that. Wich is why i'm hoping you can help out with it. I saw in one of your version updates that you got it signed trough people of OCN?

Just hoping you can help out, if not i get that 2. Then other people dont have to wonder about it 2.

**Comment by LordOfMice** [comment]
>with it is that it will only work if i disable secure boot/driver signature enforcement or test mode
Yes, it is required to run on modern x64 Windows 10 versions. And there is link on manual page that is describing problem exactly:
https://www.overclock.net/forum/375-mice/1597441-digitally-signed-sweetlow-1000hz-mouse-driver-35.html#post25560676
To run flawlessly on modern Windows 10 x64 we need a new EV certificate and perfoming Attestation signing process.

>I saw in one of your version updates that you got it signed trough people of OCN?
Yes, it is signed, but signing date is too late to run on Windows 10 x64 with Secure Boot enabled.
