### ISSUE TITLE
Having issues with overclocking not doing anything

### ISSUE THREAD

**Issue by Asuri4** [LordOfMice/hidusbf#123]
So I followed the instructions inside the 2khz - 8khz readme and they didn't do anything
Here are the steps I took

1. I opened the setup and unchecked filtering and set the polling rate back to default.  I then installed service and restarted the device

2. Now with a fresh slate I ran the 2k - 4khz file and it ran very quickly and didn't ask for permission but I assume this is normal

3. I then opened up the setup and installed the service.  Then I rebooted my computer

4. I then opened up the setup again and checked filtering on and set the polling rate to 31 for 2000hz but when I hit restart device all that happened was the biinterval went to 31 and my mouse appeared to have its dpi/sensitivity reduced severely to where I had to use my arm to click.  I don't know if that's normal for 31 polling rate but maybe that means something to you?

So maybe I messed up somewhere but upon rereading the 2k-8khz readme a couple times I think I did it step for step I also tried installing the service again after restarting my computer but that didn't change anything so maybe the 2k-4khz driver is getting blocked or something.

I greatly appreciate any help

**Comment by LordOfMice** [comment]
On modern Windows (you didn't mention version you are using) you have to follow manual from link from the end of readme.

**Comment by Asuri4** [comment]
I am using windows 10 64bit home edition.

I don't quite understand what you mean but if your talking about the non 2khz-8khz readme that says its in English the only thing it appeared to say to do was to replace the NTX86 and AMD64 folders hidusbf with the no patch one. I tried this and then redid the steps I listed in the orginal post and when I restarted the device at 31 polling the details from the column disappeared which I am assuming meant it overclocked and failed however when I redid the steps again but using the 8khz file inside the driver directory it reported a biinterval of 1 being set at 31 polling rate but when I tested it still ran at 1khz and when I tried putting the polling to 62 it did the same behavior in my original post where it put the biinterval to the polling rate.

I then put it back to 31 and instead of it being a bitinterval of 1 like it was a couple seconds of ago it went back to 31 like I stated in my original post.

So I think something is still wrong and I don't understand what I am missing/not doing. You stated that inside one of the readme's there was a link that would link me to more instructions or do I misunderstand because I couldn't find such a thing but maybe I missed it?  So if you could specify what I should be doing that would be appreciated even if its listed somewhere and I am just making you repeat yourself because I can't find what to do

Here is a screen shot showing the polling being at 31 and getting a biinterval of 1 though it was still 1000hz when I tested
![Desktop Screenshot 2022 02 06 - 06 21 25 04 (2)](https://user-images.githubusercontent.com/99102097/152686143-e2c1ef3f-0065-4f59-876e-23cedc8c380a.png)
.

**Comment by LordOfMice** [comment]
Once again. If you have trouble you have to read readme. The WHOLE readme. If there is some link with description "Recent info" you have to follow it too.
https://www.overclock.net/threads/usb-mouse-hard-overclocking-2000-hz.1589644/
