### ISSUE TITLE
Software Loadup

### ISSUE THREAD

**Issue by Fxndyk** [LordOfMice/hidusbf#126]
i had to reset my PC without deleting my files, now when i try to use the software it says " Filter Driver Service (hidusbf) is disabled or Not Installed Continue Setup? Hint: Don't forget to {Install Service} one time before anything else!" I've tried to delete the files and re-download but it just keeps popping up the same thing! When i try to overclock my controller the bar goes from green to red and disconnects my controller! Any Helppp?

**Comment by LordOfMice** [comment]
>Hint: Don't forget to {Install Service} one time before anything else!
And, of course, run setup UNZIPPED.
