### ISSUE TITLE
Controller issue/ help :(

### ISSUE THREAD

**Issue by SantiagoBerrio22** [LordOfMice/hidusbf#13]
Hello, I'm new in this community, well, I have a problem when I overclocking my controller. In fornite, when I press the keys l1 l2 r1 r2 1 time, this is like if I press the key 3 times, I can't do anything in the game. ( I don't use macros) pls help :(

**Comment by LordOfMice** [comment]
There is only one way in such situation - disable overclocking at all or try to make less overclocking. I think it is obvious.
