### ISSUE TITLE
Question: It's working but...

### ISSUE THREAD

**Issue by elnoxgdl** [LordOfMice/hidusbf#130]
Hi,

This software is working correctly but I run setup.ext install the service, select my device. BUT...
Do I need to do that every time I reboot my PC? If so, can we do it so it can load it automatically and detect the device automatically?

**Comment by LordOfMice** [comment]
No. If you have installed filter on device then it will work after every reboot. Of course, if you use hidusbf.zip only. If you have to use hidusbfp.zip then you have to know how it is working.
