### ISSUE TITLE
Driver signature with HIDUSBF

### ISSUE THREAD

**Issue by JProf09** [LordOfMice/hidusbf#131]
Hi. I've been overclocking my ps4 controller for a while using HID but have recently bought a new PC and when i click filter on device i need to restart my PC with driver signature enforcement disabled to get the controller to register. Are there any fixes for this?

**Comment by LordOfMice** [comment]
I assume you have to read readme (and link there) and pinned issue https://github.com/LordOfMice/hidusbf/issues/16
