### ISSUE TITLE
Controller OCed perfectly, but after restart it stopped working

### ISSUE THREAD

**Issue by Manic137** [LordOfMice/hidusbf#132]
I'm using a DS4 controller, although I doubt that matters. I restarted my PC to turn off the secure boot, then overclocked it successfully. I then restarted my pc again to turn off the secure boot as Apex Legends Anti Cheat requires that you have secure boot on(game would not launch with it disabled). This however caused the OC to malfunction and not work(controller wasn't usable, red bar in hidusbf). Thankfully I did not have to restart the PC to disable the OC and the controller worked again. I read there's a way to only allow hidusbf through the registry and not affect Apex Legends?

**Comment by LordOfMice** [comment]
>Apex Legends Anti Cheat requires that you have secure boot on
>I read there's a way to only allow hidusbf through the registry and not affect Apex Legends?

IDK does it help with your game (Anti Cheat engines can verify many things) but correct, it is possible to have Secure Boot On with hidusbf loaded and i personally checked this on Windows 10 x64 version 20H1 last time. 
You have to read this:
https://www.geoffchappell.com/notes/security/whqlsettings/index.htm
(WhqlSettings).
P.S. Looks like you are the first one who carefully read readme ;) This is the first right question due to 3 year.

**Comment by Manic137** [comment]
> > Apex Legends Anti Cheat requires that you have secure boot on
> > I read there's a way to only allow hidusbf through the registry and not affect Apex Legends?
> 
> IDK does it help with your game (Anti Cheat engines can verify many things) but correct, it is possible to have Secure Boot On with hidusbf loaded and i personally checked this on Windows 10 x64 version 20H1 last time. You have to read this: https://www.geoffchappell.com/notes/security/whqlsettings/index.htm (WhqlSettings). 

This did the trick for me, worked so far, I'll update if anything changes :D
![image](https://user-images.githubusercontent.com/88038453/157751167-5a1228f6-6593-46e3-89be-4ccba8ee2c4b.png)

> P.S. Looks like you are the first one who carefully read readme ;) This is the first right question due to 3 year.

Geez xD

**Comment by rstewa35** [comment]
> This did the trick for me, worked so far, I'll update if anything changes :D ![image](https://user-images.githubusercontent.com/88038453/157751167-5a1228f6-6593-46e3-89be-4ccba8ee2c4b.png)

I can also confirm this works on Windows 11 Pro x64

![hidusbf_win11_secure-boot-on](https://user-images.githubusercontent.com/70178227/158033668-9060fdf2-07b8-4766-bdb1-e0beec79a878.png)

**Comment by LordOfMice** [comment]
>I can also confirm this works on Windows 11 Pro x64

Just for completeness - try to check other identical option too:
[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\CI\Policy]
WhqlSettings:DWORD=0x00000001

First disable(delete) UpgradedSystem, of course.

**Comment by rstewa35** [comment]
> Just for completeness - try to check other identical option too: [HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\CI\Policy] WhqlSettings:DWORD=0x00000001
> 
> First disable(delete) UpgradedSystem, of course.

That key appears to work too

![hidusbf_win11_secure-boot-on-2](https://user-images.githubusercontent.com/70178227/158079354-9fc36141-b583-429e-a778-10c3a000d167.png)

**Comment by LordOfMice** [comment]
Ok, thank for checking. So there is no difference of Windows 10 and 11 right now.

**Comment by SergioVB-99** [comment]
![image](https://user-images.githubusercontent.com/101889265/159053079-8b744cf6-ee57-4e72-b445-9e37e570ce21.png)

**Comment by SergioVB-99** [comment]
Ok, this works fine in Windows 11 !!!!   Thanks
![image](https://user-images.githubusercontent.com/101889265/159059576-1930a455-2295-491d-b454-8f0e5041f35c.png)

**Comment by n00batt** [comment]
How come when I look in my command prompt, there is no whql settings, as well as none when i check in my registry editor? Do I need to do something in order to be able to see this.

**Comment by LordOfMice** [comment]
>in my registry editor

...just create new value.

**Comment by n00batt** [comment]
Sorry haha don't do this often. Managed to get it working using WhqlSettings key on windows 11.

**Comment by OsakaRider** [comment]
both UpgradedSystem and WhqlSettings work fine for me Windows 11 fresh install , but dont forget you need to restart after adding the reg key.

**Comment by sleeps-weeps** [comment]
How do I bypass secure boot I don't get the valve WhqlSettings REG_DWORD  0x1 HOW do I do that?

**Comment by LordOfMice** [comment]
Answer is few posts above.

**Comment by sleeps-weeps** [comment]
Okay thank you got it to work

**Comment by St1llest** [comment]
I'm confused. I don't know how to use the command console. How exactly should I be inputting this in the command console?

**Comment by LordOfMice** [comment]
Do you know what is "registry editor"? It is *GUI* application.

**Comment by St1llest** [comment]
> Do you know what is "registry editor"? It is _GUI_ application.

I'm learning so I know what it is, but I don't know how to use it yet. How would I set this up so that I can bypass with secure boot on?

**Comment by LordOfMice** [comment]
> I don't know how to use it yet

This question was already answered in this issue. In any case, I assume you have to use search and read something else rather than asking unrelated to THIS software questions.

**Comment by rstewa35** [comment]
I created a guide on how to do this to help those unfamiliar with the registry. You can find it [here](https://gist.github.com/rstewa35/579e6003aed35572cdecfcc888ceefd6).

**Comment by emilovz** [comment]
![image](https://user-images.githubusercontent.com/6153430/207585885-70be5149-b7c8-41d6-9c2e-972c742f0086.png)

it works but not with my wmo, any idea?

**Comment by LordOfMice** [comment]
>any idea?

1. You have to CAREFULLY read what you see on the screenshot.
2. And there is some addition:
https://www.overclock.net/threads/usb-mouse-hard-overclocking-2000-hz.1589644/post-28962318

**Comment by emilovz** [comment]
So I need the latest hidusbf which is in hidusbfn, available in the hidusbff "signed" package, which is impossible to use without atsiv/umap or test mode? I need 500hz overclock without touching atsiv,umap,test mode, secure mode on w10 22h2, that's impossible atm?

**Comment by Zts789** [comment]
> I created a guide on how to do this to help those unfamiliar with the registry. You can find it [here](https://gist.github.com/rstewa35/579e6003aed35572cdecfcc888ceefd6).

I know this is so late in the future but if you still have the guide can you make a new working link? thanks ahead

**Comment by St1llest** [comment]
Got you. Use this video. Shows it all.

https://youtu.be/my_JsBRAFsQ

**Comment by rstewa** [comment]
> > I created a guide on how to do this to help those unfamiliar with the registry. You can find it [here](https://gist.github.com/rstewa35/579e6003aed35572cdecfcc888ceefd6).
> 
> I know this is so late in the future but if you still have the guide can you make a new working link? thanks ahead

I updated the link in my original comment but I'll also add it here. You can find my written guide [here](https://gist.github.com/rstewa/579e6003aed35572cdecfcc888ceefd6)

**Comment by eriiicccc** [comment]
[``](
![image](https://github.com/LordOfMice/hidusbf/assets/118373179/57dd50f9-9192-4743-8173-e823e632679d)
)

**Comment by eriiicccc** [comment]
![image](https://github.com/LordOfMice/hidusbf/assets/118373179/dd8dea8f-6755-439d-9fdc-d21f89d470a9)

**Comment by Porknpig** [comment]
@LordOfMice  I appreciate your response but this doesn’t make any sense to me. Maybe i’m dumb but what i’m getting from this is how to enter apex legends without effecting hidusbf through the directory by enabling secure boot? I’m asking how to fix my b interval being stuck on 4 without any applications running. on 1000hz filter checked it reads binterval 4 and on 8000hz it reads binterval 1. I’ve reset and watched as many youtube videos one can watch and nothing. Could you possibly explain what I should be grabbing from issue 132?

**Comment by Porknpig** [comment]
@LordOfMice does this mean my secure boot is causing the binterval of 4? And if I change directory for it to work on windows 10 it’ll work properly and go to binterval of 1?

**Comment by rafadorock4** [comment]
This .reg file worked flawlessly in Win11-23H2 .

`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy]
"UpgradedSystem"=dword:00000000`

For those that need it, put these 3 lines above in notepad and save as .reg then open it, click yes and reboot the system.

**Comment by Adeystix** [comment]
i've tried everything including whql settings and upgraded system i still keep getting error 193 , the only way i've gotten it to work on windows 11 is by disabling memory integrity but anticheat software doesn't allow me play with integrity turned off

**Comment by Usufferance** [comment]
![afagfa](https://github.com/LordOfMice/hidusbf/assets/152410302/60b8e7f6-f451-4489-9b64-fc97472792e0)
![afdadfa](https://github.com/LordOfMice/hidusbf/assets/152410302/35fddb03-37a8-46bd-ad3e-4e2f6357d182)
![afsfsafsaf](https://github.com/LordOfMice/hidusbf/assets/152410302/09d647a5-96c5-4e29-ae0b-bed886db4b84)
![saffsafsa](https://github.com/LordOfMice/hidusbf/assets/152410302/9c2f203b-d040-43fe-aa8a-3dec2c35c8c2)


I'm Sorry I don't understand what is wrong. How do I enable  Memory Integrity. (not good with tech)

**Comment by Adeystix** [comment]
How do I enable Memory Integrity. (not good with tech)

you have to turn it off from core isolation page in windows security settings . looking for a way to get it to work without turning that setting off

**Comment by LordOfMice** [comment]
>How do I enable Memory Integrity.

I assume the answer is obvious - uninstall this software as described in readme.

> looking for a way to get it to work without turning that setting off

wiki: how could I help to make this software better: https://github.com/LordOfMice/hidusbf/issues/16#issuecomment-883918974

**Comment by no-identd** [comment]
https://winraid.level1techs.com/t/tips-discussion-usage-of-mod-signed-drivers/31158

Theoretically installing the cert in the manner outlined above should obviate needing either test signing or registry hacks

**Comment by OsakaRider** [comment]
> https://winraid.level1techs.com/t/tips-discussion-usage-of-mod-signed-drivers/31158
> 
> Theoretically installing the cert in the manner outlined above should obviate needing either test signing or registry hacks. Haven't yet tested it tho

I remember testing this before a while ago and it does not work, not to mention this is an old method if it worked this thread would be in need to begin with

**Comment by no-identd** [comment]
> > https://winraid.level1techs.com/t/tips-discussion-usage-of-mod-signed-drivers/31158
> > 
> > Theoretically installing the cert in the manner outlined above should obviate needing either test signing or registry hacks. Haven't yet tested it tho
> 
> I remember testing this before a while ago and it does not work, not to mention this is an old method if it worked this thread would be in need to begin with

All methods I've seen described so far as they relate to usbhidf don't appear to place the certificates into the correct certificate storeS. Take a close look at the Win-raid install scripts. Perhaps it won't work — I had intended to test this yesterday, but unfortunately I now won't be able to do so until in quite a few days, but I WILL test it
