### ISSUE TITLE
BInterval changes after restart

### ISSUE THREAD

**Issue by Explorertn** [LordOfMice/hidusbf#134]
Hello, 

I try to overclock my Bluetooth card, when I restart my computer the bInterval changes from 1 to another number which causes BT issues. It has to be always 1 for better stability. Also, I want to ask about the best refresh rate I can you for this card. 

Thanks

**Comment by LordOfMice** [comment]
>when I restart my computer the bInterval changes from 1 to another number

I assume the question is obvious - does "Filter On Device" stay checked after restart?

>Also, I want to ask about the best refresh rate I can you for this card.

I don't understand what is you want. The 1000 in "Selected Rate" is the best value you can get for ordinary overclocking. But it is possible to have even more overclocking, there IS link in readme.

**Comment by Explorertn** [comment]
> > when I restart my computer the bInterval changes from 1 to another number
> 
> I assume the question is obvious - does "Filter On Device" stay checked after restart?
> 
> > Also, I want to ask about the best refresh rate I can you for this card.
> 
> I don't understand what is you want. The 1000 in "Selected Rate" is the best value you can get for ordinary overclocking. But it is possible to have even more overclocking, there IS link in readme.

Thanks for replying. Yes, the Filter On Device stays checked after restart, but the bInterval changes after restart. All I want is to keep it always 1 
Concerning the Rate, I mean what is the most adequate rate for a Bluetooth wireless card if you have an idea.

**Comment by LordOfMice** [comment]
>Yes, the Filter On Device stays checked after restart, but the bInterval changes after restart.

Ok, show me "Copy IDs" dumps before restart (when bInterval = 1) and after restart.

**Comment by Explorertn** [comment]
> > Yes, the Filter On Device stays checked after restart, but the bInterval changes after restart.
> 
> Ok, show me "Copy IDs" dumps before restart (when bInterval = 1) and after restart.
This is before restart
```
Device:
"USB\VID_8087&PID_0025\5&356B5377&0&12"
"USB\VID_8087&PID_0025&REV_0002"
"USB\VID_8087&PID_0025"
  Name: Intel(R) Wireless Bluetooth(R)
  Driver: BTHUSB
  Binary: \SystemRoot\System32\drivers\BTHUSB.sys
    Path: C:\WINDOWS\System32\drivers\BTHUSB.sys
    Version: 10.0.22000.282 (WinBuild.160101.0800)
  LowerFilters: ibtusb
  BusSpeed: 1
  bInterval: 1

Controller:
"PCI\VEN_8086&DEV_A36D&SUBSYS_50071458&REV_10\3&11583659&0&A0"
"PCI\VEN_8086&DEV_A36D&SUBSYS_50071458&REV_10"
"PCI\VEN_8086&DEV_A36D&SUBSYS_50071458"
"PCI\VEN_8086&DEV_A36D&CC_0C0330"
"PCI\VEN_8086&DEV_A36D&CC_0C03"
  Name: USB xHCI Compliant Host Controller - Intel(R) USB 3.1 eXtensible Host Controller - 1.10 (Microsoft)
  Driver: USBXHCI
  Binary: \SystemRoot\System32\drivers\USBXHCI.SYS
    Path: C:\WINDOWS\System32\drivers\USBXHCI.SYS
    Version: 10.0.22000.469 (WinBuild.160101.0800)
```
And this is after restart : 

```
Device:
"USB\VID_8087&PID_0025\5&356B5377&0&12"
"USB\VID_8087&PID_0025&REV_0002"
"USB\VID_8087&PID_0025"
  Name: Intel(R) Wireless Bluetooth(R)
  Driver: BTHUSB
  Binary: \SystemRoot\System32\drivers\BTHUSB.sys
    Path: C:\WINDOWS\System32\drivers\BTHUSB.sys
    Version: 10.0.22000.282 (WinBuild.160101.0800)
  LowerFilters: ibtusb
  BusSpeed: 1
  bInterval: 1

Controller:
"PCI\VEN_8086&DEV_A36D&SUBSYS_50071458&REV_10\3&11583659&0&A0"
"PCI\VEN_8086&DEV_A36D&SUBSYS_50071458&REV_10"
"PCI\VEN_8086&DEV_A36D&SUBSYS_50071458"
"PCI\VEN_8086&DEV_A36D&CC_0C0330"
"PCI\VEN_8086&DEV_A36D&CC_0C03"
  Name: USB xHCI Compliant Host Controller - Intel(R) USB 3.1 eXtensible Host Controller - 1.10 (Microsoft)
  Driver: USBXHCI
  Binary: \SystemRoot\System32\drivers\USBXHCI.SYS
    Path: C:\WINDOWS\System32\drivers\USBXHCI.SYS
    Version: 10.0.22000.469 (WinBuild.160101.0800)
```

It's randomly changing, this time I've got the Bluetooth card with bInterval 1 before and after restart

**Comment by LordOfMice** [comment]
>LowerFilters: ibtusb

As i said above - i don't see installed hidusbf filter after and even BEFORE reboot. And i don't see Overrided.bInterval too.
You literally did NOT any overclocking.
Does the Windows ask to elevate privileges when you run setup?

>bInterval: 1

It's the fastest value for Full Speed device (and typical for bluetooth adapters) and you can't get more (except with hard overclocking but it will not work with bluetooth adapter with high probability).

**Comment by Explorertn** [comment]
> > LowerFilters: ibtusb
> 
> As i said above - i don't see installed hidusbf filter after and even BEFORE reboot. And i don't see Overrided.bInterval too. You literally did NOT any overclocking. Does the Windows ask to elevate privileges when you run setup?
> 
> > bInterval: 1
> 
> It's the fastest value for Full Speed device (and typical for bluetooth adapters) and you can't get more (except with hard overclocking but it will not work with bluetooth adapter with high probability).

Sorry I have removed the overclock, 

```
This is what it shows after restart 
Device:
"USB\VID_8087&PID_0025\5&356B5377&0&12"
"USB\VID_8087&PID_0025&REV_0002"
"USB\VID_8087&PID_0025"
  Name: Intel(R) Wireless Bluetooth(R)
  Driver: BTHUSB
  Binary: \SystemRoot\System32\drivers\BTHUSB.sys
    Path: C:\WINDOWS\System32\drivers\BTHUSB.sys
    Version: 10.0.22000.282 (WinBuild.160101.0800)
  Binary: HIDUSBF.SYS
    Path: C:\WINDOWS\System32\DRIVERS\HIDUSBF.SYS
    Version: 1.2.0.0
  LowerFilters: hidusbf,ibtusb
  BusSpeed: 1
  bInterval: 4

Controller:
"PCI\VEN_8086&DEV_A36D&SUBSYS_50071458&REV_10\3&11583659&0&A0"
"PCI\VEN_8086&DEV_A36D&SUBSYS_50071458&REV_10"
"PCI\VEN_8086&DEV_A36D&SUBSYS_50071458"
"PCI\VEN_8086&DEV_A36D&CC_0C0330"
"PCI\VEN_8086&DEV_A36D&CC_0C03"
  Name: USB xHCI Compliant Host Controller - Intel(R) USB 3.1 eXtensible Host Controller - 1.10 (Microsoft)
  Driver: USBXHCI
  Binary: \SystemRoot\System32\drivers\USBXHCI.SYS
    Path: C:\WINDOWS\System32\drivers\USBXHCI.SYS
    Version: 10.0.22000.469 (WinBuild.160101.0800)

```

**Comment by Explorertn** [comment]
And this is after another restart, it came back to 1. That's really strange 

```
Device:
"USB\VID_8087&PID_0025\5&356B5377&0&12"
"USB\VID_8087&PID_0025&REV_0002"
"USB\VID_8087&PID_0025"
  Name: Intel(R) Wireless Bluetooth(R)
  Driver: BTHUSB
  Binary: \SystemRoot\System32\drivers\BTHUSB.sys
    Path: C:\WINDOWS\System32\drivers\BTHUSB.sys
    Version: 10.0.22000.282 (WinBuild.160101.0800)
  Binary: HIDUSBF.SYS
    Path: C:\WINDOWS\System32\DRIVERS\HIDUSBF.SYS
    Version: 1.2.0.0
  LowerFilters: hidusbf,ibtusb
  BusSpeed: 1
  bInterval: 1
  Overrided.bInterval: 1

Controller:
"PCI\VEN_8086&DEV_A36D&SUBSYS_50071458&REV_10\3&11583659&0&A0"
"PCI\VEN_8086&DEV_A36D&SUBSYS_50071458&REV_10"
"PCI\VEN_8086&DEV_A36D&SUBSYS_50071458"
"PCI\VEN_8086&DEV_A36D&CC_0C0330"
"PCI\VEN_8086&DEV_A36D&CC_0C03"
  Name: USB xHCI Compliant Host Controller - Intel(R) USB 3.1 eXtensible Host Controller - 1.10 (Microsoft)
  Driver: USBXHCI
  Binary: \SystemRoot\System32\drivers\USBXHCI.SYS
    Path: C:\WINDOWS\System32\drivers\USBXHCI.SYS
    Version: 10.0.22000.469 (WinBuild.160101.0800)
```

**Comment by LordOfMice** [comment]
>Sorry I have removed the overclock, I have re-enabled it now. The bInterval is 4.

This is default value if you do not change the rate, only set filter.

>And this is after another restart, it came back to 1. That's really strange

There is nothing strange. You have to set filter AND change the rate THAN restart device.

>LowerFilters: hidusbf,ibtusb
  BusSpeed: 1
  bInterval: 1
  Overrided.bInterval: 1

THIS is successful overclocking to 1000Hz.
