### ISSUE TITLE
After extracting all, the "setup" file in the folder dissappears and is no longer there to use.

### ISSUE THREAD

**Issue by cjb48** [LordOfMice/hidusbf#135]
Ive used this program multiple times in the past with no problems. pretty straight forward. but just now when I attempted a fresh install( 6 trys) the setep.exe is not there for me to use ( windows 10)

![gitbhubissuemouse](https://user-images.githubusercontent.com/101917963/159109044-06f21305-a9fd-4f4e-838e-cc583bfc9793.PNG)
)

**Comment by cjb48** [comment]
had something to do with my antivirus, disabled it and it worked

**Comment by LordOfMice** [comment]
>had something to do with my antivirus, disabled it and it worked

Of course. JFYI, this link taken from wiki ;)
https://github.com/LordOfMice/hidusbf/issues/25
