### ISSUE TITLE
Wacom Intuos (CTL 4100) Tablet

### ISSUE THREAD

**Issue by AuracleTech** [LordOfMice/hidusbf#14]
Would this work with tablet?
We play Osu!game and we need faster refresh rate on our 200hz tablets.

**Comment by LordOfMice** [comment]
Technically this software could and will work with any USB device with Interrupt Endpoints. And now you can easily do this right in Setup.exe (pick "With Interrupts").  But whether you will get something usefull is device dependent, of course (as with any overclocking).

>our 200hz tablets
There is no such thing as 200Hz USB devices (in standard mode of using).
