### ISSUE TITLE
Dual sense Over Clock issue

### ISSUE THREAD

**Issue by bbilby27** [LordOfMice/hidusbf#141]
Hi, I guess I went to fast in the process. I attempted the overclock and my device is tagged in "with Problem" with no name on the device. Any way to set it back to normal?

**Comment by bbilby27** [comment]
![Screenshot 2022-04-14 141900](https://user-images.githubusercontent.com/62443012/163461743-11b29e1f-031f-4037-baae-0ad60d45d6d7.png)

**Comment by bbilby27** [comment]
This is the error message Im recieving

**Comment by LordOfMice** [comment]
You have to read something like readme or pinned issues.
