### ISSUE TITLE
8khz overclocking issue

### ISSUE THREAD

**Issue by GisoDsntMiss** [LordOfMice/hidusbf#148]
i would like some help because i'm trying to overclock my mices to 8khz but i think i'm doing something wrong while putting the file on the drivers folder... someone that can help me?

**Comment by LordOfMice** [comment]
I think you have to read the link to OCN from readme, there is few manuals referenced. And there are even videos exist like this: https://www.youtube.com/watch?v=pBrBtf_2abU
