### ISSUE TITLE
I somehow bricked my hitbox

### ISSUE THREAD

**Issue by Diogenesegm** [LordOfMice/hidusbf#153]
I have a custom hitbox that I pieced together with a chinese pcb (this one: https://imgur.com/a/3uITQxB), it worked fine for years. I then used hidusbf and now the inputs are randomly lost, sometimes the buttons stop working altogether, or have severe input lag. I tried unninstalling following the instructions but nothing changed. I tried different configurations, also nothing. I'm on windows 11. I even tried windows restore to a previous date. I just want to reset the configurations so my controller will work again, please help.

**Comment by LordOfMice** [comment]
You problem is unrelated to this software and with high probability has hardware source. And there is easy check to verify uninstall of driver - it shall disappear from memory and %windir%\system32\drivers folder.
