### ISSUE TITLE
tried using software with no luck

### ISSUE THREAD

**Issue by tomleeming94** [LordOfMice/hidusbf#154]
Hi, i get this error everytime, i have read through post on here and still can't fix it 

![image](https://user-images.githubusercontent.com/108104020/175433944-645f902c-af6d-4c05-a01e-ca2338806c61.png)

**Comment by LordOfMice** [comment]
I assume with "file not found" error you have to pay attention to this "absent or wrong C:\WINDOWS\SYSTEM32\DRIVERS\HIDUSBF.SYS" part of warning and try to [Install] service once again.
