### ISSUE TITLE
info

### ISSUE THREAD

**Issue by GisoDsntMiss** [LordOfMice/hidusbf#155]
is there a difference between hidusbf master and hidusbf?

**Comment by LordOfMice** [comment]
what??? master is the main and only branch in this project and the latest version of files in master branch are actual versions.

**Comment by GisoDsntMiss** [comment]
I'm asking because when i download the zip file from GitHub i thought it
was a normal version but I saw another zip around called hidusbf master so
i was wondering if there were 2 different versions


Il ven 1 lug 2022, 11:01 SweetLow ***@***.***> ha scritto:
