### ISSUE TITLE
if i try to download, windows defender tells me it found a virus

### ISSUE THREAD

**Issue by CrossyChainsaw** [LordOfMice/hidusbf#157]
![image](https://user-images.githubusercontent.com/74303221/179855924-7e5e6667-6f6a-4121-a05d-a29928e99e78.png)

**Comment by LordOfMice** [comment]
virustotal.com
And i can say that is honorably to get "Machine Learning" detection for the program written 18 years ago!

**Comment by LordOfMice** [comment]
P.S.
https://github.com/LordOfMice/hidusbf/issues/76

>malwarebytes

Looks like this is the source of problem as nothing changes...
