### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by GisoDsntMiss** [LordOfMice/hidusbf#161]
With the latest update i heard it's possible to overclock controllers to 8khz like it is possible for the zaunkoenig?

**Comment by LordOfMice** [comment]
Where did you find this statement? "high speed devices support" is just correct information about such devices in setup, not the new function.

**Comment by GisoDsntMiss** [comment]
On some discord, they said they were able to overclock controllers to 8khz and i was just curious about it

**Comment by LordOfMice** [comment]
Once again. Driver itself has possibility to overclock ANY device literally from the first release day. But value you feed to driver depends from setup and setup did not have code to correctly process high speed devices.

>they were able to overclock controllers to 8khz and i was just curious about it

2k-8k overclocking is unrelated to the last changes in setup. And just follow the link in readme if you wish to know how to do this.

**Comment by GisoDsntMiss** [comment]
So basically following the readme instructions for 2k/8khz you can overclock any device?

**Comment by LordOfMice** [comment]
Yes. But whether you will get something useful depends on device as with any overclocking.
