### ISSUE TITLE
Is it possible to overclock a controller connected with the Cronus zen ?

### ISSUE THREAD

**Issue by vxynnn** [LordOfMice/hidusbf#162]
hi, I wanted to ask if it was possible to overclock a controller connected via Cronus zen I tried but the imput delay is always the same

**Comment by LordOfMice** [comment]
>Cronus zen

IDK what is that. This software works with any USB devices. Аnd if device is visible in Setup (with Interrupts or USB or All filters) then you can try to overclock it.

>but the imput delay is always the same

You should read about overclocking to higher USB speed class. Setup now warns for such case for Low Speed to Full Speed overclocking.

**Comment by vxynnn** [comment]
I tried to connect it via this device but it gives me 10ms of delay with the ps5 controller 
if instead I connect it normally 0 ms

**Comment by vxynnn** [comment]
the device in question and the Cronus zen serves to improve the aim and other things so

**Comment by LordOfMice** [comment]
>via this device
This is processing delay. It's normal as processing has some time to be executed and can not fixed outside this device.
