### ISSUE TITLE
Error Code 577

### ISSUE THREAD

**Issue by stoobah** [LordOfMice/hidusbf#164]
Hey, I'm getting the error code 577 when trying to "Filter on Device" for my PS4 Dualshock 4 V2 Controller.
I have read that disabling "Secure Boot" in the BIOS does work, but I'm wondering if there is another fix.
When I disable "Secure Boot" in BIOS I am unable to launch Valorant until I restart my PC to re-enable Secure Boot.
Is there any other fix? Thank you for your suggestions in advance.

Greeting,

stoob

**Comment by CrimsonsMyth** [comment]
Look at the other closed issues for your answer

**Comment by LordOfMice** [comment]
Thank @CrimsonsMyth
