### ISSUE TITLE
What can i do if my mouse doesnt downgrade either , how can i change the driver or do whats required .

### ISSUE THREAD

**Issue by TeslaMaker** [LordOfMice/hidusbf#17]
When i filter with downgraded the mouse doesnt work until i unfilter it .

**Comment by LordOfMice** [comment]
1. You have to read readme. Notes with exclamations there are really important.
2. I think the last version of setup.exe will give you some message when you try to set filter on you device.

**Comment by TeslaMaker** [comment]
i turned off secure boot and how do i check whether min is non Microsoft USB stack?

**Comment by LordOfMice** [comment]
"doesnt work" and "turned off secure boot" are mutual exlusive.
