### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by Noneed2explain** [LordOfMice/hidusbf#171]
Hey, tysm for creating this programm and letting us all use it for free (: My problem is that every time i overclock my controller its just perfect and the difference is huge and so good but it only last for like 5 minutes before i can just feel how damn much input delay i got without it. ): So this is why i have to restart the overclocking so many times that it got me to write this. /: Please help me and thanks in advance. :D

**Comment by LordOfMice** [comment]
https://github.com/LordOfMice/hidusbf/issues/170
