### ISSUE TITLE
Error Code 1060 Help 

### ISSUE THREAD

**Issue by Syyxxx** [LordOfMice/hidusbf#172]
I'm getting an error code of 1060
I read about the last time you spoke with someone else about hidsubf or something, but idk where to find that and also i clicked install service it didn't do anything i need help please reach my discord syyxx6#5916 thanks

**Comment by LordOfMice** [comment]
https://github.com/LordOfMice/hidusbf/issues/28
+
google: error 1060 hidusbf

>please reach my discord syyxx6#5916

I think you slightly misunderstand the rules of communication.

**Comment by Unknownplyr** [comment]
Did you find a solution I have the same issue
