### ISSUE TITLE
Setup opens for half a second then disappears

### ISSUE THREAD

**Issue by Taktic123** [LordOfMice/hidusbf#174]
Hello, Im using a windows 10 PC with full permissions. I downloaded, extracted from zip, then attempted to open setup regularly then as an administrator but it will not open the application. I checked task manager and it isn't running in the background. I've tried uninstalling and reinstalling, but the same problem arises. Please advise!

**Comment by LordOfMice** [comment]
First read wiki page about anti-viruses. And second check Windows events, there is usually presents record about refusal to launch application or about application error (exception).
