### ISSUE TITLE
Can't overclock low speed mode mouse

### ISSUE THREAD

**Issue by 4ymnoy-doktor** [LordOfMice/hidusbf#175]
Hello. I can't get the Low-Speed mode mouse to overclock more than 125Hz... I have Intel xHCI with microsoft drivers and windows 11 22H2 (22621). How can I solve the problem?

**Comment by LordOfMice** [comment]
https://www.overclock.net/threads/usb-mouse-hard-overclocking-2000-hz.1589644/post-29028485
