### ISSUE TITLE
Scuff Controller Reflex FPS (Filter On Device Error)

### ISSUE THREAD

**Issue by julesmoretti** [LordOfMice/hidusbf#178]
Hello Lord of Mice:

When installing this on my new build windows 11 I get the following error only when filter on device is enabled:

<img width="307" alt="Screenshot 2022-10-01 152538" src="https://user-images.githubusercontent.com/744300/193430636-1b63a5f8-c599-420e-b2a5-e51780a20385.png">

<img width="716" alt="Screenshot 2022-10-01 122532" src="https://user-images.githubusercontent.com/744300/193430641-e920b9c5-7f46-4fb1-aeaf-219b119b7172.png">

Any advice would be great! Thank you!

**Comment by LordOfMice** [comment]
I think you have to read readme, wiki or PINNED issue:
https://github.com/LordOfMice/hidusbf/issues/16
