### ISSUE TITLE
Error trying to test filter service: 193

### ISSUE THREAD

**Issue by BoshJeach** [LordOfMice/hidusbf#179]
Had 0 issues with the service until the recent windows update that apparently broke the ability for me to overclock the driver. I get the following error that says it will likely crash & then upon restart it indeed does crash. I've tried editing the registry as per the #132 thread with no success. Tried both reg edits (one at a time, not at same time!) & neither solved the issue. Restarted after each edit. Tried different usb ports, uninstalling & reinstalling the driver, etc. 

This is on a W11 pro build. I can't turn off secure boot due to requirements of other games. Any help greatly appreciated, thanks!

EDIT: Verified that turning off memory integrity solves the issue. I'd prefer to leave that on. Heading to BH10 now & will check the other threads further when I get home.

**Comment by LordOfMice** [comment]
>Error trying to test filter service: 193

Pinned issue:
https://github.com/LordOfMice/hidusbf/issues/54

>Verified that turning off memory integrity solves the issue. I'd prefer to leave that on.

Pinned issue:
https://github.com/LordOfMice/hidusbf/issues/16
