### ISSUE TITLE
Real performance issues

### ISSUE THREAD

**Issue by Carmelo98** [LordOfMice/hidusbf#180]
Hello, have you noticed a visibile performance drop when changing the polling rate?
In my testing, when overclocking, for example, a controller, there is a significant fps drop in almost every game. Also on cinebench benchmark, without touching the controller, you will get a worse score, even when forcing 500hz instead of 1000. If device is unplugged, score returns to normal.

**Comment by LordOfMice** [comment]
>Also on cinebench benchmark, without touching the controller, you will get a worse score, even when forcing 500hz instead of 1000. If device is unplugged, score returns to normal.

Never seen this. There is some small memory access footprint from old USB controllers even when devices inactive, but it's hard to note. Modern xHCI controllers touch memory only on some data transfers from/to device.

>In my testing, when overclocking, for example, a controller, there is a significant fps drop in almost every game.

This completely depends on game input engine. And modern engines (expect high input rate) require less processor time than old.

And yes, try to check that you don't have any hooks on input from third party software, of course.
