### ISSUE TITLE
Hidusbf overclocking error 

### ISSUE THREAD

**Issue by Nuke1216** [LordOfMice/hidusbf#181]
I'm receiving two problems where I download the Hidusbf for overclocking my controller and after i "extract all" I get this first pop up that's asking me to download an app from the app store when I click on setup, but no app is available. Then my second problem is when I download the app and don't extract the driver file, I'm able to access the setup to continue the process to overclocking controller but I'm lead with another problem that says " Filter driver Hidusbf is disabled or not installed" if i click continue setup my controller line becomes a red line. Please help I am on windows 11 if that matters 
![Driver error ](https://user-images.githubusercontent.com/116605837/197648391-4af63738-3434-4986-bfc0-81dd3e7f3ea7.png)
![Hidusbf](https://user-images.githubusercontent.com/116605837/197648406-b015385e-32e2-4e84-aa28-e9da54c26ffd.png)

**Comment by LordOfMice** [comment]
It's time to read readme and wiki. You have to extract .zip content and install hidusbf service before anything else. But it is NOT complete list you have to do on Windows 11.

**Comment by Nuke1216** [comment]
Hey is there anyway I could contact you via phone to have you walk me
through this Im not understanding the read me section honeatly I’m so
confused when it comes to pc things

**Comment by LordOfMice** [comment]
No. And there are enough manuals (texts and videos). Just google "hidusbf".
