### ISSUE TITLE
i got an error message when i tried to overclock my controller and now when i try and plug it into my pc it doesnt even turn on

### ISSUE THREAD

**Issue by tkxnz** [LordOfMice/hidusbf#182]
I have been looking all over the internet but can't find a solution

**Comment by tkxnz** [comment]
also my controller is a wired razer wolverine V2 xbox controller

**Comment by tkxnz** [comment]
also the number showed up as a 4 instead of a 1 next to my controller

**Comment by LordOfMice** [comment]
1. "error mesage" is not descriptive
2. there is section about unistalling software in the readme 
3. read pinned issues and wiki
