### ISSUE TITLE
Need help lord of mice

### ISSUE THREAD

**Issue by RagedOutGaming** [LordOfMice/hidusbf#186]
I have the program up and ready and try to install service nothing happens what do i do?
![Screenshot 2022-11-06 003026](https://user-images.githubusercontent.com/110763341/200154275-628ecaeb-b9c9-4092-844e-350e8bc3222c.png)

**Comment by LordOfMice** [comment]
>try to install service nothing happens

Why do you think so? Move to the next step - restart your "Xbox Gaming Device" on the screenshot...
