### ISSUE TITLE
Error 1060 help! Secure boot disabled gigabyte board

### ISSUE THREAD

**Issue by Harrypall23** [LordOfMice/hidusbf#187]
Hello I keep getting the attached errors even when disabled secure boot.

![Uploading 27755F90-29DB-44AB-89B4-4B0F3C6A3BEE.jpeg…]()

any ideas

**Comment by Harrypall23** [comment]
![Uploading 13BEC741-98AF-4765-B9AB-8CF64ED5EB7E.jpeg…]()

**Comment by LordOfMice** [comment]
1. I don't see any screenshot.
2. 
https://github.com/LordOfMice/hidusbf/issues/172
https://github.com/LordOfMice/hidusbf/issues/28
