### ISSUE TITLE
winver //  22H2

### ISSUE THREAD

**Issue by xelmXIV** [LordOfMice/hidusbf#189]
Good morning. 
since updating to windows version 22H2 (OS Build 19045.2311), i'm wondering if that affected the overall clock speed at which my controller was able to achieve.  previously my overclocking speed on my dualsense [ps5] controller went from [default] 3.5ms to 0ms. 
but now, it overclocks to only 0.3-0.6 ms. i say this because it's fluctuating. when i achieved 0ms it was never jumping around. just constant 0 which was awesome. so i'm wondering if there's a way to fix it or revert without having to downgrade windows versions.

are you currently on windows version 22H2 and have experienced this problem?
if not, do you have any suggestions and will there be any updates soon? 

Kind regards,

~xelm

**Comment by LordOfMice** [comment]
>are you currently on windows version 22H2
Yes.
https://www.overclock.net/threads/usb-mouse-hard-overclocking-2000-hz.1589644/post-29079398

>have experienced this problem?
No. As i don't have your hardware, of course.

>do you have any suggestions
Try any latency optimization guide as usual.

>will there be any updates soon?
No.
