### ISSUE TITLE
Xbox arcade stick cannot unistall.

### ISSUE THREAD

**Issue by MadaoDev** [LordOfMice/hidusbf#190]
Hello,

So the problem i am experiencing is that after i did apply the driver once for my xbox arcade stick after that it stopped working on PC.

i tried the Uninstall from readme but it remains as device with problem.
I tried uninstalling the device but nothing helps (that used to solve the problem on my previous pc)

Not sure what to do. My device works fine with other PCs.

**Comment by LordOfMice** [comment]
>I tried uninstalling the device but nothing helps (that used to solve the problem on my previous pc)

Why do you think that after uninstalling device through Device Manager you have problem with THIS software?

>Not sure what to do.

Show me the [CopyIDs] result.
