### ISSUE TITLE
Collective Minds Strike Pack Dominator 

### ISSUE THREAD

**Issue by Neptune1520** [LordOfMice/hidusbf#192]
Is there a way to overclock the Collective Minds Strike Pack Dominator to under 1 ms? I am able to make it slower but I am not able to make it faster. Is this something you are able to do on your end?

**Comment by LordOfMice** [comment]
Excerpt from manual:
> to be 100% sure of the result it's good to know before trying to test NEW device that your SYSTEM allows such kind of overclocking with help of one of the "tested and approved" devices listed below.

Do you have other device that you can overclock to under 1 ms on your system?
