### ISSUE TITLE
driver uninstall issue

### ISSUE THREAD

**Issue by jelenko20** [LordOfMice/hidusbf#193]
![image](https://user-images.githubusercontent.com/60643499/208270104-90c638f4-87d8-4007-945b-01ab28a8bb30.png)
Hi, i can't reenable core isolation becouse of HIDUSBFU.sys. 
How to uninstall please?

**Comment by LordOfMice** [comment]
I assume "Uninstall" section in readme, eh?

**Comment by jelenko20** [comment]
I did that, but it just installs it. When i go to core isolation it is
there preventing turning it on.

**Comment by LordOfMice** [comment]
>I did that

Did what? Because script for uninstalling can't INSTALL anything,
