### ISSUE TITLE
not working in windows 10

### ISSUE THREAD

**Issue by TheOldZeref** [LordOfMice/hidusbf#195]
![image](https://user-images.githubusercontent.com/28839467/210131437-45d35f64-bdfb-4a77-8fa3-52964346fd06.png)
I already installed the driver in windows 7/8.1 but when i update to windows 10 it stopped work

**Comment by TheOldZeref** [comment]
![image](https://user-images.githubusercontent.com/28839467/210132415-c70b5296-985f-405d-a881-cb7cacc1e1cb.png)
I used the folders of hidusbfn and this happen as you can see i have secure boot off

**Comment by LordOfMice** [comment]
>as you can see i have secure boot off

readme:
DRIVER folders are intended for REPLACEMENT of
original HIDUSBF drivers and under x64 versions of OS
will run in Test Mode ONLY!

Test Mode On != Secure Boot Off

and JFYI:
https://github.com/LordOfMice/hidusbf/issues/16#issuecomment-1368260189
