### ISSUE TITLE
PS4 Controller set to 1000hz but is not coming close to 1000hz in Xinput test 

### ISSUE THREAD

**Issue by Ragingl2** [LordOfMice/hidusbf#196]
I followed tutorials perfectly, my friend who has done this a bunch of times did it for me through parsec and yet my controller still is not overclocked. 

Filter is YES, Rate says 1000hz and Interval says 1. The correct device is selected. I'm completely stumped 

![Screenshot 2023-01-15 011918](https://user-images.githubusercontent.com/122685337/212479357-6f2577f4-b993-4cc7-8081-6f8d921dd0d8.png)
![Screenshot 2023-01-15 012233](https://user-images.githubusercontent.com/122685337/212479496-19d24ca7-f0e3-476d-82c5-4aae4968a8c0.png)

**Comment by LordOfMice** [comment]
Yes, something unusual.
But isolation of problem is NOT unusual.

1. Reboot first.
2. If you can then try other OS instance on this PC.
3. Try this device on other PC.
