### ISSUE TITLE
error 557

### ISSUE THREAD

**Issue by augustrl** [LordOfMice/hidusbf#197]
How long do you think it will take to fix this issue i constantly use this and i have to have secure boot enabled im also on windows 11 so the registry settings hasnt worked so far

**Comment by LordOfMice** [comment]
>How long do you think it will take to fix this issue

It's time to read the first pinned issue:
https://github.com/LordOfMice/hidusbf/issues/16#issuecomment-883918974

>so the registry settings hasnt worked so far

It's time to read the second pinned issue:
https://github.com/LordOfMice/hidusbf/issues/132#issuecomment-1065956330
