### ISSUE TITLE
hidusbf kill my controller help me plz 

### ISSUE THREAD

**Issue by iTrOzola** [LordOfMice/hidusbf#198]
When I tried to use hidusbf, my controller is turned off and since Windows no longer detects it,Thank you for helping me

![Capture d’écran 2023-02-03 214359](https://user-images.githubusercontent.com/124400919/216707121-a3af8dd2-8a06-4619-a06c-0ff7df94063b.png)

**Comment by iTrOzola** [comment]
![image](https://user-images.githubusercontent.com/124400919/216719842-70e8acc0-75b7-4e49-8f77-68bb55a01f3f.png)

**Comment by iTrOzola** [comment]
![image](https://user-images.githubusercontent.com/124400919/216719940-76bac3fd-ea14-4fdc-ab35-4da2ea9014ad.png)

**Comment by LordOfMice** [comment]
1. Uninstall section of readme.
2. If you posted screenshot why did you select WORKING device rather than non working? What is logic of your action???
