### ISSUE TITLE
Controller not reconnecting

### ISSUE THREAD

**Issue by Starrob16** [LordOfMice/hidusbf#199]
I have a Microsoft elite 2 controller, I did all the steps but when I disconnected my controller and reconnect it to see if it worked, my controller does not work anymore. I changed the cable and have tried resetting my PC I have done pretty much everything I know. The Xbox light just flashes but it doesn't actually connect. When I connect and disconnect the cable the controller vibrates like if its getting power so I don't know what the issue can be. Can someone please help me.

**Comment by LordOfMice** [comment]
If you think that problem is this software then just uninstall it. There is section in readme how to do this.
