### ISSUE TITLE
USB Input Device corruption

### ISSUE THREAD

**Issue by RandomGuy3015** [LordOfMice/hidusbf#2]
Be careful with downloading this. Once I downloaded it and applied a polling of 125Hz (From 500Hz), my mouse stopped working. I got my mouse working again by plugging it into a different usb port, but even now the usb port that the mouse was previously in is corruped. Acually, it's only corrupted for my mouse. If I plug my keyboard in there it works fine, so I have no idea what happend. If my mouse isn't plugged into the corrupted usb port, device manager says my usb port is working properly. When my mouse is plugged into the corrupted usb port, device manager reports "**Windows cannot start this hardware device because it's configuration information (in the registry) is incomplete or damaged. (code 19)**
![screenshot 4](https://user-images.githubusercontent.com/48179101/53695798-5aece300-3dc0-11e9-83f8-fb864a00b9d2.png)

btw the 'mouse' (blackwidow elite) is acually a keyboard, my computer just thinks it's a mouse

**Comment by LordOfMice** [comment]
Just read readme before using software and, much more important, before posting "errors".
