### ISSUE TITLE
binterval stuck on 4 regardless of changes can't get to 1 

### ISSUE THREAD

**Issue by babygrizz** [LordOfMice/hidusbf#202]
Hi, followed readme and tried other steps shown on youtube. 

Can't seem to get my binterval to reset to 1. Always stuck on 4. I notice that when I click filter on device, then install service, there is no Open request. When I watch youtubers doing this, they get a further Open request modal. I do not. 

Please help, thank you for your time / attention.

Device:
"USB\VID_054C&PID_0CE6\5&17FC267&0&11"
"USB\VID_054C&PID_0CE6&REV_0100"
"USB\VID_054C&PID_0CE6"
  Name: USB Composite Device
  Driver: usbccgp
  Binary: \SystemRoot\System32\drivers\usbccgp.sys
    Path: C:\Windows\System32\drivers\usbccgp.sys
    Version: 10.0.22621.1194 (WinBuild.160101.0800)
  Binary: HIDUSBF.SYS
    Path: C:\Windows\System32\DRIVERS\HIDUSBF.SYS
    Version: 1.2.0.0
  LowerFilters: hidusbf
  BusSpeed: 2 (High)
  bInterval: 4
  Overrided.bInterval: 4

Controller:
"PCI\VEN_8086&DEV_43ED&SUBSYS_86941043&REV_11\3&11583659&1&A0"
"PCI\VEN_8086&DEV_43ED&SUBSYS_86941043&REV_11"
"PCI\VEN_8086&DEV_43ED&SUBSYS_86941043"
"PCI\VEN_8086&DEV_43ED&CC_0C0330"
"PCI\VEN_8086&DEV_43ED&CC_0C03"
  Name: USB xHCI Compliant Host Controller - Intel(R) USB 3.20 eXtensible Host Controller - 1.20 (Microsoft)
  Driver: USBXHCI
  Binary: \SystemRoot\System32\drivers\USBXHCI.SYS
    Path: C:\Windows\System32\drivers\USBXHCI.SYS
    Version: 10.0.22621.1194 (WinBuild.160101.0800)

OS: NT x64 (amd64)

<img width="713" alt="2023-03-02 10_06_43-USB Devices Rate Setup" src="https://user-images.githubusercontent.com/126770433/222397547-416d7b89-637f-4e05-8f59-98df38f34d27.png">

**Comment by LordOfMice** [comment]
>BusSpeed: 2 (High)

This is High Speed Device. bInterval = 4 IS 1000Hz for such devices. And if you select 8000Hz you will get bInterval = 1.
