### ISSUE TITLE
Hidusbf controller overclock

### ISSUE THREAD

**Issue by Thomas98767** [LordOfMice/hidusbf#208]
Does hidusbf need to be open at all times for your controller to be overclocked?

**Comment by LordOfMice** [comment]
Driver can not be "Open" or "Closed". Driver can be "Loaded" and then "Participates in driver stack for device". And the technique that hidusbf uses (it is lower filter driver) requires the last.
On the other hand running Setup.exe is not required, of course. It is _setup_.

**Comment by Thomas98767** [comment]
> Driver can not be "Open" or "Closed". Driver can be "Loaded" and then "Participates in driver stack for device". And the technique that hidusbf uses (it is lower filter driver) requires the last.
> On the other hand running Setup.exe is not required, of course. It is _setup_.

Why does it feel different when i have the setup application open or closed? Is it just a placebo?

**Comment by LordOfMice** [comment]
It is.
