### ISSUE TITLE
Can’t install service

### ISSUE THREAD

**Issue by CRK2D** [LordOfMice/hidusbf#210]
why cant I install service? help

**Comment by LordOfMice** [comment]
with high probability you have broken .inf file handler. check this and fix

**Comment by CRK2D** [comment]
yes it says something aboy inf file how do I fix tho?

**Comment by LordOfMice** [comment]
this question is OS related and unrelated to this software

**Comment by CRK2D** [comment]
so there’s no fix? I got win 10 pro

**Comment by LordOfMice** [comment]
>so there’s no fix?

There is fix, but you are asking this question in WRONG place.
