### ISSUE TITLE
I dont know what to do here

### ISSUE THREAD

**Issue by martinsv04** [LordOfMice/hidusbf#211]
![image](https://user-images.githubusercontent.com/123270059/230256314-da62fc49-8c68-485a-a0fb-459dd202896c.png)
Same thing when I opened the archive unzzipped or in the folder
Also when i rebbot the pc the usb ports die and i cant use the mouse and keybord in the usb i was using them befor installing

**Comment by LordOfMice** [comment]
>Also when i rebbot the pc the usb ports die and i cant use the mouse and keybord in the usb i was using them befor installing

1. I think you may have some OTHER message from setup before one you show. Something about service that does not install or can not run.
2. and AMD controller on you screenshot does not allow some kind of overclocking - the highest possible overclocking.
