### ISSUE TITLE
struggling to overclock BT connected wireless controller

### ISSUE THREAD

**Issue by St1nGxD** [LordOfMice/hidusbf#214]
this worked for when it was wired, but i can't get it to work when its connected with BT... thanks in advance.

![image](https://user-images.githubusercontent.com/95598517/232306639-1c490fb9-a4f8-4d0c-bc1b-4518dc032c45.png)
![image](https://user-images.githubusercontent.com/95598517/232306673-d2e77d81-6ddd-48b5-b208-98d826b9b48a.png)

**Comment by LordOfMice** [comment]
wireless part of communication channel can have (and usually has) its own restriction in addition to USB part

**Comment by St1nGxD** [comment]
not following, what does this mean? what should i do?

**Comment by LordOfMice** [comment]
Nothing. It's overclocking, sometimes it does NOT work. And usually wireless devices are not oveclockable because they are wireless.
