### ISSUE TITLE
Legion 5 pro - Mouse oc NEVER works

### ISSUE THREAD

**Issue by emmcue-thanks** [LordOfMice/hidusbf#216]
Legion 5 pro
5800H cpu
windows 10 LTSC 1809 
Build 17763
tried on many mouses and no luck
tried on an intel cpu laptop and it worked

does this mod work on AMD laptops?

**Comment by LordOfMice** [comment]
>does this mod work on AMD laptops?

Only the in the same USB speed class. And this (AMD/Asmedia USB host controller restrictions) is described in link (RECENT INFO) from readme.

**Comment by emmcue-thanks** [comment]
What do you mean by on the same USB speed class? i tried on all ports it did not work.
Should i use a USB hub as a middle and hope it oc?
