### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by FlawlessLGA** [LordOfMice/hidusbf#217]
Ive followed the videos to install the lordofmice controller overclock but im still getting the below message.

Ive tried the registery fix where you create the new 'UpgradedSystem'

I get this when i press filter on device. Ive already installed service before this.

![lordofmice](https://user-images.githubusercontent.com/131495147/233740862-b634480a-2147-471c-84ec-8e4c3641373a.png)

**Comment by LordOfMice** [comment]
> Ive already installed service before this.

 No, you don't.
Check . INF file association.
