### ISSUE TITLE
Help, Error 1060

### ISSUE THREAD

**Issue by Jacobzo00** [LordOfMice/hidusbf#218]
"The specified service does not exist as an installed service" Something (Windows 10 x64 with Secure Boot, antivirus, protection/anticheat engine, broken installation of service, absent or wrong

C:\WINDOWS\SYSTEM32\DRIVERS\HIDUSBF.SYS, hidusbf.sys from hidusbfN.zip without Tes Mode on x64, enforced kernel code loading policy, etc.) prevents filter service from running; device will stop functioning after [Restart] with high probability, continue Setup?

Any suggestions on how to fix it. I was OC my Xbox elite series 2 controller, "filter on device", then this appeared. I've been using this software for almost a full year now and never have I ever ran into this issue/error.

**Comment by LordOfMice** [comment]
[Install Service] button before anything else.
If it does not help then uninstall service as described in readme and then install it once again. And reboot after uninstall.
