### ISSUE TITLE
hidusbfn.zip 

### ISSUE THREAD

**Issue by einfachphillip** [LordOfMice/hidusbf#22]
filter driver service (hidusbf) is disabled or not installed 
but yesterday it works by my controller... i think i do something shit pls need help cant play games with 5ms delay XD

**Comment by LordOfMice** [comment]
Setup->Install Service once again, eh?
If this will not help - HIDUSBF.INF->Install as readme recommends.

**Comment by GeniusRepair1** [comment]
**### CAN'T I OVERCLOCK MY CONTROLLER, ERROR CODE 577**

Hey, guys not sure if this will help, but I tried this method, and it worked for me. I was having the same issues fighting back and forth. I have a found solution; I have tried it myself without losing any of your files. Thank you; look at that link below hope this helps  https://www.youtube.com/watch?v=2iAVjU9lknM&t=1s
