### ISSUE TITLE
Error 193 !

### ISSUE THREAD

**Issue by TreyBSM** [LordOfMice/hidusbf#220]
I tried to overlock my Dualsense Edge controller but got 193 error when tried to checkmark "Filter on device" and the solution to resolve this issue was to get into Windows Security, then Device Security. Then under Core Isolation I had to toggle off Memory Integrity to get my controller fully overlocked and functional. 

Windows 11 Pro 22H2
Os Build: 22621.1555

PC Specs:
i9 13900k
32 GB DDR5 @5600mhz
AMD Radeon RX 7900XT

**Comment by LordOfMice** [comment]
PINNED issue:
https://github.com/LordOfMice/hidusbf/issues/54
