### ISSUE TITLE
Issue with Windows 11 .. enabling/disabling secure boot .. Apex Legends will no longer run smoothly 

### ISSUE THREAD

**Issue by Hctsyuhbeazy** [LordOfMice/hidusbf#222]
My issue is a bit complex, & I’m still not clear on what the exact culprit of the problem is so please bear with me. 

This issue started when my PC auto updated to Windows 11, I didn’t think anything of it and was actually getting used to it.

This was until I wanted to play some Valorant .. but was met with an error screen telling me I had to enable secure boot in order to open the game. 

So I enabled secure boot and surely I was able to play Valorant.

My issue began a couple days later when I wanted to play Apex Legends (which I usually play on Controller) .. I noticed my input lag was insanely high so I checked DS4 and it read 3.5ms input delay 

I then tried to fix my overclock settings and stupidly ignored the warning that told me if I installed the service it would leave my device unusable 

After remembering that I enabled secure boot, I went and disabled it .. (thinking this would be the quick fix to my issue)

I was able to get my controller overclocked again, and went to play Apex Legends .. but was met with the same input lag issue .. 

I ended up factory resetting my apps .. (didn’t work) factory reset and formatted all of my drives.. (didn’t work) 

(Went back to Windows 10)

Not really sure if it’s an issue with BIOS settings clashing with Hidusbf .. a corrupt driver.. something to do with the registry file..  

But I really just want to be able to run Apex Legends smoothly again while using my controller

(currently my Apex Legends experience is the feeling of running through quicksand/mud while being sucked in by a infinite horizon ult)

If anyone has some ideas for a solution please let me know, thanks

**Comment by LordOfMice** [comment]
>I enabled secure boot, I went and disabled it

https://github.com/LordOfMice/hidusbf/issues/132

> input lag issue 

First of all - recheck that you really overclock device, not simply install hidusbf as filter for device.
You did not show result of  [Copy IDs] nor screenshot of Setup even so it is unknown what you really did.
