### ISSUE TITLE
I lose frames when i overclock 

### ISSUE THREAD

**Issue by alexanderadreon** [LordOfMice/hidusbf#224]
This software used to work perfectly fine for me with ds4 but recently i been trying to use it and when i overclock my frames in fortnite are in the 30-40s even lower so i tried dsx and had the same problem when i un overclock it works perfectly fine and my frames go back to 180-200 plus any reason why this is happening?

**Comment by LordOfMice** [comment]
From Wiki:
Higher CPU consuming or some anomalies in software behavior after overclocking: https://github.com/LordOfMice/hidusbf/issues/201
