### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by FYINDICATORS** [LordOfMice/hidusbf#228]
how to delete this from my computer?

**Comment by LordOfMice** [comment]
Exactly as described in readme

**Comment by FYINDICATORS** [comment]
nah. there is no file to unistall, yet i cannot turn on memory integrity because of Hidusbf.sys. cant find this shit anywhere

**Comment by LordOfMice** [comment]
>there is no file to unistall
 
Really? Reread readme (exactly Uninstall section) once again and try to understand what you are reading.
