### ISSUE TITLE
Driver error

### ISSUE THREAD

**Issue by HElpmelo** [LordOfMice/hidusbf#229]
![Screenshot 2023-05-31 115309](https://github.com/LordOfMice/hidusbf/assets/135164445/bfdc6dfc-06c7-4bef-b98f-a5821023af09)

I tried to install application with my controller and my mouse but then this happened,
pls help.

**Comment by LordOfMice** [comment]
I think you have to read warnings when you get them.
https://github.com/LordOfMice/hidusbf/issues/132
https://github.com/LordOfMice/hidusbf/issues/54
readme ->uninstall
