### ISSUE TITLE
Setup frozen when I hit "install service"

### ISSUE THREAD

**Issue by SW3D3N** [LordOfMice/hidusbf#231]
title is self-explainatory, when I hit install service the setup freezes and plays the window error sound everytime I click somewhere. I cannot click anywhere and I can't even close the application to restart. I'm following this tutorial: https://www.youtube.com/watch?v=zHEFrEyrLAQ 
With the goal of making my games on ps4 controller less delayed. My controller is bluetooth connected.

**Comment by LordOfMice** [comment]
> I hit install service the setup freezes and plays the window error sound everytime I click somewhere

check .inf file association

>My controller is bluetooth connected.

this is USB overclocking tool
