### ISSUE TITLE
Ps5 Controller Interval stuck on 4 

### ISSUE THREAD

**Issue by Porknpig** [LordOfMice/hidusbf#233]
I’ve reset my drivers on controller, deleted all files from hidusbf. Redownloaded hidusbf master file. Unzipped hidusbf not hidusbfn with winrar. I get “setup” which used to be “setup.exe” not sure if that has anything to do with it. Selected All, found controller checked filter, and selected rate 1000. I Installed service, and restarted. I unplugged, and plugged back in. Binterval shows up as 4 which used to be 1. Had to reset pc due to unknown error. Any help or advice would be gladly appreciated!

**Comment by LordOfMice** [comment]
>Had to reset pc due to unknown error. 

Check pinned issues, particularly https://github.com/LordOfMice/hidusbf/issues/132
