### ISSUE TITLE
Overclocking Bricked My Controllers

### ISSUE THREAD

**Issue by chromeposites** [LordOfMice/hidusbf#235]
I tried overclocking my Xbox Elite Series Controller and now it won’t work properly. I got hit with the Getting an error 577 when trying to "filter on device" and needing to disable driver signature when trying to apply the filter. Now when I try to run a game like rocket league, it only puts me as player two and can only control the menu with the mouse. What can I do? I tried using another controller and the same thing. Just totally wiped my PC and it seems like the same issue. I was on windows 11 so that may have messed it up. Now im stuck with a $200 controller and can’t use it on PC.

When I do a test of my controller on browser, it shows a  Controller 1 and Controller 2. Controller 1 has no input, and controller 2 has the input.

I read some stuff that you can go on steam and edit the general controller settings, but they recently updated steam and its no longer a setting…. Please help.

**Comment by LordOfMice** [comment]
>needing to disable driver signature

Pinned issue:
https://github.com/LordOfMice/hidusbf/issues/132
