### ISSUE TITLE
PS5 controller stopped working after changing polling rate to 4k

### ISSUE THREAD

**Issue by lvl2pidgey** [LordOfMice/hidusbf#237]
Hi, I tried using this for my PS5 controller but the controller wont work now... After connecting to the PC it immediately disconnects and the bluetooth doesn't work anymore either. So I can't even uninstall the changes. Would you have any recommendations? @LordOfMice

**Comment by LordOfMice** [comment]
>Would you have any recommendations? @LordOfMice

Of course. readme Warnings and Uninstall, Pinned Issue https://github.com/LordOfMice/hidusbf/issues/132

>and the bluetooth doesn't work anymore either

Why do you think that you don't have problem with controller itself? Bluetooth connection does not controlled by hidusbf at all.
