### ISSUE TITLE
help before i go crazy

### ISSUE THREAD

**Issue by Annika1986** [LordOfMice/hidusbf#238]
sorry for my english am from germany. I have a big problem with Hidusbf Controller OC. I've been using it for 6 months now. The installation went really well. And now the following problem. Since the beginning I have had the problem that the software keeps failing. I'm in the middle of the game and suddenly notice my delay is back. When the program is running everything is like butter on my PS5 controller. I have to keep unplugging the cable from the controller and plugging it back in then it works again. Until it's gone again. It keeps stopping working sporadically in the game. It's not because of the controller/cable/usb hub, everything was rushed through.
The Hidusbf program has been cleanly uninstalled and reinstalled several times. Windows 10 has also been completely reinstalled. I am advisable and in need of help so much. Do you have an idea or a tip what it could be that the software keeps blocking? But why does it work when the controller is plugged in again. Where is the mistake here. I am very sad. There isn't a day where it runs continuously. I have a high-end PC, the power supply was EVERYTHING tested, no errors. Something must be blocking the software from time to time. Do you have a tip?
Thanks very much
LG

**Comment by Annika1986** [comment]
@LordOfMice  ♥️

**Comment by LordOfMice** [comment]
No, I personally didn't meet such problem and the source(s) of problem is (are) unknown in general. As you can see from other issues with the same symptom it is hard to detect.

**Comment by Annika1986** [comment]
@LordOfMice Yes I have seen that some people have this problem. I was just hoping you guys have an idea why it doesn't work all the time. because I can't constantly plug the controller on and off in the game. something on the system prevents the OC all the time
