### ISSUE TITLE
fps dropping using hidusbf and i deleted the software and the same issue is showing up

### ISSUE THREAD

**Issue by ssssssssddfrf** [LordOfMice/hidusbf#239]

**Comment by LordOfMice** [comment]
This kind of overclocking is not persistent so if you uninstall software then you return to original state.

**Comment by Annika1986** [comment]
@LordOfMice but isn't it the case once you overclock the usb port that it stays that way? until you set the default again?

**Comment by Annika1986** [comment]
@ssssssssddfrf I think your system wasn't strong enough for that, because I don't have any fps drops

**Comment by LordOfMice** [comment]
> but isn't it the case once you overclock the usb port that it stays that way? until you set the default again?

> i [b]deleted[/b] the software and the same issue is showing up

if you uninstall this software you definitely reset ALL devices to they default values
