### ISSUE TITLE
Minor help

### ISSUE THREAD

**Issue by Yourboymusti** [LordOfMice/hidusbf#240]
The Hidusbf.sys driver is incompatible with memory integrity (core isolation). Is there no bypass at all? Is this final? Installing the Sweetlow certificate into the trusted root in Windows didn't work, and installing the inf didn't either. The secure boot bypass is easy enough, but the memory integrity is the main issue. Can you look into it, or should I just give up and leave it off?
I don't care about the security aspect, but the CoD anti-cheat flags accounts/pcs with secure boot/tpm/core isolation disabled, leading to shadowbans. I've got 2 out of 3 working, so I should be fine, but it'll be better if I have all 3 enabled. 

Thank you 

![incompat](https://github.com/LordOfMice/hidusbf/assets/30542495/00582a1e-dd81-479a-9fab-81674f293b00)

**Comment by LordOfMice** [comment]
> Is this final? 

https://github.com/LordOfMice/hidusbf/issues/16#issuecomment-883918974
