### ISSUE TITLE
Frame drops on controller when overclocked / When not overclocked frames are normal ( CAN SOMEONE HELP )

### ISSUE THREAD

**Issue by Jordyk01** [LordOfMice/hidusbf#247]
Hi, I've been getting frame stutters and drops when using hidusb, multiple people are having the same issue and i was just wondering if there is a fix to this issue as this program is amazing for controller pc on fortnite.
![FPS DROPS](https://github.com/LordOfMice/hidusbf/assets/140527769/2af4d612-72d6-45fb-acd7-00d9dea21740)

**Comment by LordOfMice** [comment]
https://github.com/LordOfMice/hidusbf/issues/201
