### ISSUE TITLE
BInterval 6 to 4

### ISSUE THREAD

**Issue by PapaPorter69** [LordOfMice/hidusbf#248]
Ive over clocked probably 10 different controllers and theyve all worked perfect through out the years. But for some reason it reset now and every time I try to overclock it my BInterval GOES FROM 6 TO 4 INSTEAD OF 6 TO 1. Never had this issue before any known fixes.

**Comment by LordOfMice** [comment]
You are using USB High Speed device and select 1000Hz as overclocking. If you will select 8000Hz you get bInterval 1. But I don't understand why you are checking bInterval at all...
