### ISSUE TITLE
setup.exe is deleting itself

### ISSUE THREAD

**Issue by oskarjhk** [LordOfMice/hidusbf#25]
whenever I press install service setup.exe closes and deletes itself. I have disabled secure boot and am running on 64-bit Windows 10.

**Comment by oskarjhk** [comment]
https://user-images.githubusercontent.com/68066983/102938753-d42d5c80-44a4-11eb-8f68-b21c12e3ebef.mp4

**Comment by LordOfMice** [comment]
it is VERY hard to delete executable module on modern Windows itself. check you AV or something like this.

**Comment by oskarjhk** [comment]
> It is VERY hard to delete executable module on modern Windows itself. Check your AV or something like this.

what is an AV

**Comment by LordOfMice** [comment]
Google "AV acronym", there is the first definition. Is is not smart question.

**Comment by oskarjhk** [comment]
> Google "AV acronym", there is the first definition. It is not smart question.

ok, but how would I check whether the antivirus is affecting the software you didn't respond to that part of the question. I've googled it and it says to check here to allow any programs through the firewall but I don't know what setup.exe would be called here  

![image](https://user-images.githubusercontent.com/68066983/103012825-0d60dd80-4534-11eb-8b06-314bfa8f01b0.png)

**Comment by LordOfMice** [comment]
If you can not distinguish between anti-virus and firewall I have one clear recommendation - or educate yourself or find someone who can help you.

**Comment by oskarjhk** [comment]
> If you can not distinguish between anti-virus and firewall I have one clear recommendation - or educate yourself or find someone who can help you.

I DONT HAVE AN ANTIVIRUS THE ONLY THING WHICH COULD BE BLOCKING YOUR SOFTWARE IS MY FIREWALL

**Comment by supernayru** [comment]
lord of mice you are no help at all

**Comment by supernayru** [comment]
> If you can not distinguish between anti-virus and firewall I have one clear recommendation - or educate yourself or find someone who can help you.

you fucking suck at helping people and expect people to just know things
work on your patience you stupid faggot.
