### ISSUE TITLE
Restart doesnt work. ERROR

### ISSUE THREAD

**Issue by eternalmeow1** [LordOfMice/hidusbf#250]
![Bild_2023-09-08_135536991](https://github.com/LordOfMice/hidusbf/assets/144450761/65286741-55d3-48ee-bd88-a96998556edb)
like i clicked on restart and this is what happend. Tbh im not sure if my controller is overclocked now or not. What should i do against this error
![Bild_2023-09-08_135705036](https://github.com/LordOfMice/hidusbf/assets/144450761/b6a9aa0f-c5f6-4324-8a27-80fb10c9d3e3)

**Comment by LordOfMice** [comment]
You have to read recommendation in message.

**Comment by eternalmeow1** [comment]
wym?

**Comment by LordOfMice** [comment]
The fact that you are not native English speaking DOES NOT free you from understanding messages. Use translator.

"You can try to disconnect and then reconnect device or reboot system."

**Comment by eternalmeow1** [comment]
and if i reconnect my controller, will my controller be overclocked then?

**Comment by LordOfMice** [comment]
Yes.

**Comment by Fakeyy23** [comment]
I have the same issue. Rebooting pc or disconnecting device doesnt help and error remains. Only way I dont get the error is if i hit restart while having ds4 running.
