### ISSUE TITLE
My controllers still behaving with hidusbf even after I had uninstalled it as is in the documentation 

### ISSUE THREAD

**Issue by mariosdesign** [LordOfMice/hidusbf#252]
I have uninstalled everything as mentioned in the documentation, but my controllers are still experiencing increased latency, which I find undesirable during gameplay.

is there any way to remove it completely and fix this issue with my controller and bring it back to the original behaviour?

**Comment by LordOfMice** [comment]
After uninstalling hidusbf service through hidusbfU.inf there is no chance for driver to load at all.
