### ISSUE TITLE
ps5 controller overclock giving pc lag

### ISSUE THREAD

**Issue by paulobkr** [LordOfMice/hidusbf#254]
hi after i overclocked my ps5 controller my computer started to lag in games (fortnite but i tested it on dayz and it's also lagging) does anyone know what it could be or how to solve it?

**Comment by paulobkr** [comment]
I think I solved the problem by closing the Geforce experience overlay and parsec (another piece of software I use that runs in the background).

**Comment by LordOfMice** [comment]
Project Wiki: Higher CPU consuming or some anomalies in software behavior after overclocking: https://github.com/LordOfMice/hidusbf/issues/201
