### ISSUE TITLE
Somehow it kind of clones my controller input (?)

### ISSUE THREAD

**Issue by every1knowsace** [LordOfMice/hidusbf#256]
I don't really know what's happening there but by playing Rocket League the game detects there is another controller ready to be connected and if i press "options" (I'm using a DS4 and "options" is the key to join shared screen mode) it basically detects another player as if it is connecting to play, While in game both of the "players" have the same controller input so both move identically if i do something. Help me please D:
![Cattura](https://github.com/LordOfMice/hidusbf/assets/148139630/fef20796-7fee-40a1-8673-fa6ebec7ddfb)
![Cattura2](https://github.com/LordOfMice/hidusbf/assets/148139630/e8c3de47-ecd2-435a-af3a-581e57876a40)
![Immagine 2023-10-16 203101](https://github.com/LordOfMice/hidusbf/assets/148139630/85ef8c2e-3a8d-4f1a-9760-08129ae5935d)

**Comment by LordOfMice** [comment]
I don't see any problem with THIS software.
