### ISSUE TITLE
lost frame on fortnite when i use it pls resolve it 

### ISSUE THREAD

**Issue by predatorttv** [LordOfMice/hidusbf#259]
lost frame on fortnite when i use it pls resolve it , i disable geforce experience, i tried to unistall ds4 and tried antimicro and it work for a little but the problem its back today

**Comment by LordOfMice** [comment]
https://github.com/LordOfMice/hidusbf/issues/201
You shoud try to insulate the source of problem yoursel, it's unrelated to this software. And problem can lay inside game input engine.
