### ISSUE TITLE
Controller softbricked?

### ISSUE THREAD

**Issue by baccpack** [LordOfMice/hidusbf#26]
Got a brand new PS4 controller that I was gonna use for CoD and after filtering my device it went red and blank on hidusbf. Everytime I plug it in it windows says "USB not recognized." When I try to go back into the software, it tells me not to filter on a device with a problem. How can I fix my controller? PLEASE HELP!

**Comment by LordOfMice** [comment]
Read readme. It's so easy.

**Comment by LordOfMice** [comment]
Ok. But your have one of two possible problems - or something broken in your operating system or your controller is HARDbriked. After deleting device this software no more loaded for this device. You can check this in device manager:
![image](https://user-images.githubusercontent.com/39810206/103373458-129acb00-4ae6-11eb-971a-7a635ff4a357.png)
