### ISSUE TITLE
When using my controller overclocked i get major fps drop

### ISSUE THREAD

**Issue by Rivezi** [LordOfMice/hidusbf#260]
on Fortnite with my controller not plugged in I get high 300 to mid 400fps when i plug in my controller while its over clocked I go to 150-230 I uninstalled msi and turned off GeForce overlay didn't work

**Comment by LordOfMice** [comment]
https://github.com/LordOfMice/hidusbf/issues/201
You shoud try to insulate the source of problem yoursel, it's unrelated to this software. And problem can lay inside game input engine.
