### ISSUE TITLE
error 193 even with whql settings and upgraded system reg keys 

### ISSUE THREAD

**Issue by Adeystix** [LordOfMice/hidusbf#261]
i've tried everything including whql settings and upgraded system i still keep getting error 193 , the only way i've gotten it to work on windows 11 is by disabling memory integrity but anticheat software doesn't allow me play with integrity turned off.  same on my laptop and desktop

**Comment by LordOfMice** [comment]
>anticheat software doesn't allow me play with integrity turned off

wiki: how could I help to make this software better https://github.com/LordOfMice/hidusbf/issues/16#issuecomment-883918974
