### ISSUE TITLE
Getting an error 577 when trying to "filter on device"

### ISSUE THREAD

**Issue by Usufferance** [LordOfMice/hidusbf#262]
![Screenshot 2023-11-29 093103](https://github.com/LordOfMice/hidusbf/assets/152410302/75b476ce-16a5-41eb-8dfd-43e75a3a5e2e)

I'm not very good with tech and came cross this problem trying to overclock my controller .

![Screenshot 2023-11-29 093255](https://github.com/LordOfMice/hidusbf/assets/152410302/3a5fbd5a-ab03-49e5-8da6-d5651a534dfb)

**Comment by LordOfMice** [comment]
Do not replicate the name of the PINNED Issue, read it:
https://github.com/LordOfMice/hidusbf/issues/16
and too
https://github.com/LordOfMice/hidusbf/issues/132
