### ISSUE TITLE
keyboard and mouse not working HELP PLS

### ISSUE THREAD

**Issue by ajjjj3** [LordOfMice/hidusbf#263]
I installed hidusbf then once i pressed restart by keyboard and mouse stop working and now dont know what to do pls help. I've already tried restarting my pc , unplugging the usbs, drivers method, please help I dont know what to do

**Comment by LordOfMice** [comment]
>I've already tried restarting my pc , unplugging the usbs, drivers method, please help I dont know what to do

readme->Uninstall

>keyboard and mouse stop working

PINNED Issues:
https://github.com/LordOfMice/hidusbf/issues/16
https://github.com/LordOfMice/hidusbf/issues/132

And the last but not least - I assume you got some message when try to restart but ignored it.
