### ISSUE TITLE
Causes Performance Issues

### ISSUE THREAD

**Issue by okbruhlol** [LordOfMice/hidusbf#264]
Overclocking has issues with using too much CPU, making games studder or lose lots of FPS, please fix this.

**Comment by raritytiks** [comment]
> Overclocking has issues with using too much CPU, making games studder or lose lots of FPS, please fix this.

You are raising the clock rate, your CPU has to keep up. This is not a bug. This is like cranking up an amplifier up to 11 and complaining that your audio is distorted.

**Comment by LordOfMice** [comment]
wiki: 
Higher CPU consuming or some anomalies in software behavior after overclocking: https://github.com/LordOfMice/hidusbf/issues/201
and narrowed to games - use the games with RIGHT input engines...
