### ISSUE TITLE
ERROR 193 on microsoft surface pro 7 +

### ISSUE THREAD

**Issue by Dmtdreamer** [LordOfMice/hidusbf#269]
Hello

I  would like to overclock my Xbox Controller on my Microsoft Surface 7 plus.
But when checking filter on device I got error 193.

I saw that maybe reset secure bootnkey should work but I can only disable it on UEFI panel.

Here is the message I got on the software when trying to change my controller input lag value

![Capture d’écran 2023-12-28 150103](https://github.com/LordOfMice/hidusbf/assets/155085808/ae3770fc-daf6-4cff-b17e-798b837d1de3)

Maybe there is another way to fix it?

**Comment by LordOfMice** [comment]
PINNED issue:
https://github.com/LordOfMice/hidusbf/issues/54
