### ISSUE TITLE
not able to overclock here

### ISSUE THREAD

**Issue by 151fallen151** [LordOfMice/hidusbf#273]
cant get it to overclock or activate the driver for some reason what am i missing here this is the error message i keep getting when i try to change the settings 
![Screenshot 2024-01-02 130732](https://github.com/LordOfMice/hidusbf/assets/155504951/0efd43f8-bbc5-41bb-899d-762d586c2c48)
![Screenshot 2024-01-02 130732](https://github.com/LordOfMice/hidusbf/assets/155504951/88258263-f75c-4384-abfc-c357914a95a4)

**Comment by LordOfMice** [comment]
PINNED issue:
https://github.com/LordOfMice/hidusbf/issues/54
