### ISSUE TITLE
Overclocking | device to default | 

### ISSUE THREAD

**Issue by 87MILAN** [LordOfMice/hidusbf#274]
**I have a question about overclocking the device in hidusbf |
How do I restore my device to default operation? | and the last question is whether hidusbf interferes with the devices selected for overclocking, I mean, for example, headphones, microphone, and if they were accidentally overclocked, would they be damaged?**

ps: thx for you time and help <3 @LordOfMice

**Comment by LordOfMice** [comment]
>How do I restore my device to default operation?

readme -> uninstall

>would they be damaged?

No.
