### ISSUE TITLE
Error 577 

### ISSUE THREAD

**Issue by Sinasharifi123** [LordOfMice/hidusbf#276]
Hello it’s been a week I had a problom with error 577 and you just answerd my 3 issue ticket but it’s not working please can you answer me I tried everything I had disable secure boot and all that please help me I had this problom the whole last week please don’t just answer with other people problems you replied me all that.

**Comment by LordOfMice** [comment]
I assume you slightly misunderstand the purpose of issues. If you don't understand that you have the SAME problem as other people before you - it is not the problem of this software.
