### ISSUE TITLE
Dual sense and Dual sense edge controllers showing incorrect values.

### ISSUE THREAD

**Issue by astrixx** [LordOfMice/hidusbf#278]
Hey guys. 

The PS5 controllers the Dualsense and the newer Dualsense edge and aren't being read properly by the app in my opinion.

These controllers can be overclocked to 1000hz like the previous PS4 controllers. On those and some very early PS5 controllers when you set the refresh rate to 1000hz the binterval =1. 
With the new batches of the PS5 dual sense they show stock at the 250hz a binterval of 6 and when overclocked to 1000hz it shows up as binterval 4.

With these PS5 controllers there are extra options, like like 2000hz 4000hz and 8000hz. Setting it to 8000hz get the binterval to 1 but it's not helping the controller. There is no way these controllers support 8000hz but people dont understand this. I heard that setting 8K only resends the same data not any new so it creates input lag and wastes CPU usage.

The new PS5 dual sense edge supports 1000hz out out of the box so in hidusbf it shows up as binterval 4-6. No need to overclock it but strangely you don't get the speed benefit unless you run it as a virtual PS4 controller in DS4 windows then it overclocks or just uses the speed it should be at either overclocked or in the edge's case on default. What is causing this?

I think in my opinion the hidUSBf isn't reading the PS5 controllers right. Not sure if it was a firm ware update that broke that but I have seen a very limited PS5 controllers having 1 binterval at 1000hz, possibly only early releases from 2nd party controllers to their partners (certain large warzone streamers).

Problem is there are so many videos telling people to overclock to 8000hz but there is no way it even supports that. The default is 250hz on a regular dual sense and it can be overclocked to 1000hz and the edge supports 1000hz natively but not sure why you need DS4 Windows and run it as a virtual PS4 to actually get the input overclock or just actually using 1000hz. Maybe windows 10 and 11 isn't reading it properly either?

I'm not a coder but spent many hours working out how to get the OC to work on my controllers, Problem is they stopped supporting and discontinued DS4 windows and trying to get people to use DSX V3 but that doesn't take advantage of the higher hz and if it does not for long as it's buggy and ends up being slow or no OC or lower latency. I wonder if you guys could add native support for the PS 5 controllers and fix the polling rates above 1000hz when I know it can't run at. I get super fast speeds on 1000hz with DS4 on my dualsense. So many people making videos telling people to use 8K which is just wrong.

**Comment by LordOfMice** [comment]
>I think in my opinion the hidUSBf isn't reading the PS5 controllers right

1. HIDUSBF is generic tool, it can't read one device right and other wrong.
2. As with any overclocking one device is better than other and this is almost unrelated to polling rate you can setup.
