### ISSUE TITLE
Overclocking issues

### ISSUE THREAD

**Issue by MarvinsvbC** [LordOfMice/hidusbf#279]
Alr so I overclocked my controller and the first time it worked. I did it again and doesn’t work. Idk why it doesn’t work no more but I tried deleting it and downloading and it still didn’t work and resetting my controller on pc. Any help

**Comment by skhanal5** [comment]
What do you mean by it didn't work?

**Comment by MarvinsvbC** [comment]
> What do you mean by it didn't work? My delay was on 0 and then when back to 4ms

**Comment by LordOfMice** [comment]
>resetting my controller on pc

Readme -> Uninstall
