### ISSUE TITLE
Applied 1000hz but It stills in 125

### ISSUE THREAD

**Issue by Idontknowbruhh** [LordOfMice/hidusbf#281]
(sorry for my english)

Hi, I would like some help here please.

As you can see in the imgs, for some reason when I activate the 1000hz they don't really work, even though the program says they do. I used to use this program on Windows 8 with the same peripherals and it worked perfectly... please help, I really need those 1000hz

![Uploading 20240128_181950.jpg…]()
![Uploading 20240128_181936.jpg…]()
![Uploading 20240128_181940.jpg…]()

**Comment by LordOfMice** [comment]
I assume you got some warning when try to set 1000Hz on this device. Do NOT ignore it. Read the link from readme about recent information.
