### ISSUE TITLE
Hello again!

### ISSUE THREAD

**Issue by Idontknowbruhh** [LordOfMice/hidusbf#282]
As you said the first time I was here, I read the warning messages, I also read the manual, I installed and uninstalled everything and nothing works. Could it be a problem with some driver? And if so, how can I solve it? In case you were wondering, the filter is applied, the program reduces the polling rate, but it does not exceed 125. I thought I could solve it by doing some research, but I couldn't do anything

**Comment by LordOfMice** [comment]
> I also read the manual
> the filter is applied, the program reduces the polling rate, but it does not exceed 125

I see you read manual but I see that you did not read it **whole** too. Because you omited some vital information once again.
