### ISSUE TITLE
please help!

### ISSUE THREAD

**Issue by Soulecy** [LordOfMice/hidusbf#285]
every time i use the hidusbf my fps drops insanely amount. it happened on fortnite, destiny 2, injustice 2. i even tested it when i remove the overclock. so i know it isnt anything else but the software. i have a regular ps5 controller. and i switched from 8000 to 4000 to 2000 to even 1000hz still does the same thing. i really want to use this software but it just makes my game stutter n drops my fps so much where its unplayable n to fix it i have to move mouse or press a key on my keyboard.

**Comment by LordOfMice** [comment]
wiki:
Higher CPU consuming or some anomalies in software behavior after overclocking: https://github.com/LordOfMice/hidusbf/issues/201
