### ISSUE TITLE
Anti-cheat

### ISSUE THREAD

**Issue by agueroq8** [LordOfMice/hidusbf#288]
I overclock my ps5 controller and play about a week no problems, i don't know why try to open memory integrity after that the anti cheat give my account shadow banned, i don't use any cheat 
I read about recochet (thats anti-cheat software for call of duty) 
That's used kernel level security checking the drivers on the kernal it's possible get ban from using hidusbf ?

**Comment by LordOfMice** [comment]
I did not see any problem with THIS software. Ask about ban policy there you banned, not here.
