### ISSUE TITLE
Error 193 without disable memory integrity 

### ISSUE THREAD

**Issue by Tomshuu** [LordOfMice/hidusbf#289]
Hey yo, just a quick question, i really dont find any answers online, so i want to overclock my ds4 but when i do it the normal way i get the error 193, found a fix with disable in core isolation memory integrity, but due to using the pc for everything so banking etc too, i wanna have the more secruity, so is there a way to fix error 193 with disable it ?

**Comment by LordOfMice** [comment]
>so is there a way to fix error 193 with disable it ?

how could I help to make this software better: https://github.com/LordOfMice/hidusbf/issues/16#issuecomment-883918974
