### ISSUE TITLE
Controller setup gone wrong

### ISSUE THREAD

**Issue by rvlxnd** [LordOfMice/hidusbf#29]
Okay after pressing install service on my selected controller, i then change the rate to 1000 and filter on devices, after i install service that way, my controller option has been selected as red, and when i go and play a game, the controller isnt detected
![Screenshot (1)](https://user-images.githubusercontent.com/77421393/104532208-51944a80-55d5-11eb-8cb1-8dedf17ce635.png)
![Screenshot (2)](https://user-images.githubusercontent.com/77421393/104532243-62dd5700-55d5-11eb-848c-e01c9963ac18.png)

**Comment by LordOfMice** [comment]
You have to read readme
