### ISSUE TITLE
Overclock Mouse to 1000hz in win 11

### ISSUE THREAD

**Issue by xKrinZx** [LordOfMice/hidusbf#290]
Hello! I am currently facing an issue and need a help on that. I previously used the overclocking software on my win 10 and it worked perfectly fine. But after I upgraded to win 11, game like valorant doesn't let secure boot being disabled. And I tried using the regedit method, it didn't show any error in the setup software, however my hz is still the same. If I run it when secure boot is disabled it reaches 1000 mhz. Any idea how can I make my mouse run in 1000 pooling rate with secure boot enabled?

**Comment by LordOfMice** [comment]
What is "regedit method?". To load driver under recent versions of 10x64 or 11x64 with Secure Boot enabled the only public available method is https://github.com/LordOfMice/hidusbf/issues/132
But if you try overclock the USB Low Speed device you have to pay attention on setup warning.
