### ISSUE TITLE
turning off secure boot makes me unable to play valorant with this.

### ISSUE THREAD

**Issue by KGT-MAX** [LordOfMice/hidusbf#299]
As it says, I'm trying to make my polling rate upto 1khz on my keyboard but when turning the filter on, it shows the error. I know disabling secure boot is required but valorant does not allow secure boot to be turned off when playing the game. Any other work arounds?

**Comment by LordOfMice** [comment]
**Pinned** issue https://github.com/LordOfMice/hidusbf/issues/132
