### ISSUE TITLE
Windows 1903 can't overclock a mouse that used to be overclockable

### ISSUE THREAD

**Issue by westonlast** [LordOfMice/hidusbf#3]
A year or so ago I was able to overclock this cheap HP mouse using this.  Now I won't go above the default 125 Hz, but I can downclock to 62 and 31 Hz.

Maybe Microsoft changed binary compatibility yet again?

I'm in test mode, too, by the way.

**Comment by LordOfMice** [comment]
>Maybe Microsoft changed binary compatibility yet again?
Yes, they did. But it shall fixed in the latest hidusbfn.zip (as stated in commit).
If you never tried this - welcome to
https://www.overclock.net/forum/375-mice/1589644-usb-mouse-hard-overclocking-2000-hz.html
as readme recommends.
