### ISSUE TITLE
GENERIC USB CONTROLER HOST NOT COMPATIBLE

### ISSUE THREAD

**Issue by hidusalx** [LordOfMice/hidusbf#301]
![image](https://github.com/LordOfMice/hidusbf/assets/173551162/626f32f1-7a0f-40cf-9e4e-72b59678493b)

PLEASE HELP, i saw that issue#22 it was the same or similar issue but i dont rally understand what to do because im spanish and i dont too much english

**Comment by hidusalx** [comment]
Before the red square was shown another error was shown first,it was this one
![image](https://github.com/LordOfMice/hidusbf/assets/173551162/d8b62a67-f8e2-4bba-8a44-9e8cade12c6b)

**Comment by hidusalx** [comment]
i want to add that my secure boot is off,also de device i want to overcolck its a simple ps5 controller(the edge one)

**Comment by LordOfMice** [comment]
In order to try:
1. [Install Service] button
2. Manual install of HIDUSBF.INF
3. Check .INF file association

**Comment by KaiTheDestroyee** [comment]
How can I manually install HIDUSBF.INF / HIDUSBF_AS.INF
cuz my controller is completly not working after it is red 
![Screenshot 2024-08-10 125412](https://github.com/user-attachments/assets/8a2ee5fb-614b-47b3-aad3-e4b4c8362463)

**Comment by adambouchane27-ship-it** [comment]
hey please i wanna use hidusbf with memory integrity to play valorant how can i solve this issue please ?
