### ISSUE TITLE
Sweet Low Security Certificate

### ISSUE THREAD

**Issue by djiverson03** [LordOfMice/hidusbf#304]
Hello. I am on Windows 11 Pro and been using hidusbf for overclocking my PS5 controller. I had to turn memory integrity off to use it, but I am suspecting it being off is causing crashes to my PC when using it. I have diagnosed my PC with benchmarks to see if it was a hardware issue, but it was not. I wanted to ask if having memory integrity off can cause performance issues such as sudden crashes? I also get a lot of error messages in my Event Viewer saying "Ran out of Memory". Lastly, are we supposed to install the certificate from the Sweet Low file to run the OC more efficiently? Thank you.

**Comment by LordOfMice** [comment]
> I wanted to ask if having memory integrity off can cause performance issues such as sudden crashes?

No. It is protection against some drivers (weak signed from MS point of view) like HIDUSBF.SYS. These drivers CAN did bad things leading to crashes but OTOH the well signed drivers can do this things too.

>my Event Viewer saying "Ran out of Memory".

HIDUSBF driver does not consume any memory during its normal work, it is pure **filter** driver

>Lastly, are we supposed to install the certificate from the Sweet Low file to run the OC more efficiently?

SweetLow.CER certificate has zero impact on ability to load HIDUSBF.SYS driver on modern OSes, it just the way to verify integrity of files in package.
