### ISSUE TITLE
Install service not working

### ISSUE THREAD

**Issue by Sbezyyy** [LordOfMice/hidusbf#305]
I press install service and the window for the open page doesn’t pop up any fix?

**Comment by Sbezyyy** [comment]
![image](https://github.com/LordOfMice/hidusbf/assets/173880733/4ba3f3a2-45bd-40b7-b53a-431b46aeb45e)

**Comment by LordOfMice** [comment]
1. Why do you think that service did not installed?
2. https://github.com/LordOfMice/hidusbf/issues/301
