### ISSUE TITLE
BusSpeed Issues

### ISSUE THREAD

**Issue by E3Lemon** [LordOfMice/hidusbf#306]
On every other device than my controller, the BusSpeed is running at 1 (Full Speed), however regardless of what I do on my ps5 controller, it runs at variable 2 (High), in which the difference between the two is very noticeable. I have tried many different ports, cables, and controllers so it seems like a hardware or driver issue which I have checked many times, but I am simply left in confusion for how every device except the one I need is running at full speed. Here is the copied ID.

Device:
"USB\VID_054C&PID_0CE6\5&3296ACEA&0&10"
"USB\VID_054C&PID_0CE6&REV_0100"
"USB\VID_054C&PID_0CE6"
  Name: USB Composite Device
  Driver: usbccgp
  Binary: \SystemRoot\System32\drivers\usbccgp.sys
    Path: C:\WINDOWS\System32\drivers\usbccgp.sys
    Version: 10.0.19041.4474 (WinBuild.160101.0800)
  Binary: HIDUSBF.SYS
    Path: C:\WINDOWS\System32\DRIVERS\HIDUSBF.SYS
    Version: 1.2.0.0
  LowerFilters: hidusbf
  **BusSpeed: 2 (High)**
  bInterval: 4
  Overrided.bInterval: 4

Controller:
"PCI\VEN_8086&DEV_A2AF&SUBSYS_09611028&REV_00\3&11583659&0&A0"
"PCI\VEN_8086&DEV_A2AF&SUBSYS_09611028&REV_00"
"PCI\VEN_8086&DEV_A2AF&SUBSYS_09611028"
"PCI\VEN_8086&DEV_A2AF&CC_0C0330"
"PCI\VEN_8086&DEV_A2AF&CC_0C03"
  Name: USB xHCI Compliant Host Controller - Intel(R) USB 3.0 eXtensible Host Controller - 1.0 (Microsoft)
  Driver: USBXHCI
  Binary: \SystemRoot\System32\drivers\USBXHCI.SYS
    Path: C:\WINDOWS\System32\drivers\USBXHCI.SYS
    Version: 10.0.19041.4355 (WinBuild.160101.0800)

OS: NT x64 (amd64).

**Comment by LordOfMice** [comment]
PS5 Controller IS High Speed USB Device.
JFYI, High Speed is "speedier" than Full Speed.
