### ISSUE TITLE
Error message when hitting Restart

### ISSUE THREAD

**Issue by Fakeyy23** [LordOfMice/hidusbf#307]
Everytime i hit restart in setup i always get an error message saying it if doesn't restart by 10 seconds then something is wrong. How do i fix this issue. Only time i dont get that message is when i restart while having DS4 running. If i hit restart without ds4 it doesn't work

**Comment by LordOfMice** [comment]
1. You can fix this exactly as message recommends - disconnect and reconnect device or reboot OS.
2. "doesn't work" is completely non-descriptive.

**Comment by Adaye1e** [comment]
But this problem is causing input lag issues when i use DS4 windows.
