### ISSUE TITLE
My controller dualshock 4 isnt overclocking

### ISSUE THREAD

**Issue by rhinomon1** [LordOfMice/hidusbf#309]
Hi LordOfMice, how are you?

Controller: DualShock 4 PS4 Wireless
Windows 10 Pro - 22H2 19045.4651
USB Port: 3.0

I'm having an issue. I'm using my PS4 controller on PC via cable, and when I overclocked it, the input lag in DS4Windows remained at 3.5ms (the same as before overclocking). I'm not sure if it's a DS4Windows bug or if it's not actually working properly. I've looked through your resolved cases, but haven't found a solution to this problem. I've tried all the tutorials available, but haven't been able to resolve it.

I think I might be missing something important. I've read and re-read the README, but couldn't figure it out on my own. Could you help me with this?

Thank you!

**Comment by LordOfMice** [comment]
If bInterval changes after overclocking and you have Full Speed device then THIS software did its job.
