### ISSUE TITLE
Controller output not registering properly after 8000hz overclock

### ISSUE THREAD

**Issue by GPlays09** [LordOfMice/hidusbf#311]
I know my controller is outputting at 8000hz but in game (aimlabs for example) the maority of the packets aren't either parsed properly or detected in the first place is there a way to check if this is a driver issue or the game's?

Also would you be so kind to provide a game that is know to support 8000hz?

**Comment by LordOfMice** [comment]
Wiki: 
Higher CPU consuming or some anomalies in software behavior after overclocking: https://github.com/LordOfMice/hidusbf/issues/201

>Also would you be so kind to provide a game that is know to support 8000hz?

No. But you can study something like this:

https://us.forums.blizzard.com/en/overwatch/t/new-feature-%E2%80%93-high-precision-mouse-input-gameplay-option/422094

to know what do you need for smooth input.
