### ISSUE TITLE
app crashes when a xbox 360 controller is inserted

### ISSUE THREAD

**Issue by RandomGreenKirb** [LordOfMice/hidusbf#312]

**Comment by LordOfMice** [comment]
I assume "crashes" means some message with error.

**Comment by RandomGreenKirb** [comment]
nope just straight up crashes and the program will refuse to open until the controller is unplugged

**Comment by LordOfMice** [comment]
I don't know what do you mean by "crash", but that is what I mean:
![image](https://github.com/user-attachments/assets/10f660a2-41da-4b25-a55c-a32eeb3175eb)
