### ISSUE TITLE
Controller not being recognized whenever I overclock it

### ISSUE THREAD

**Issue by NHawkster** [LordOfMice/hidusbf#313]
For some reason whenever I try to overclock it, the name of the controller disappears.  The bInterval also shows nothing.  I do not know what to do, I have tried rebooting my computer and changing things in the registry.  I also disabled driver signature enforcement. 

I made sure to click Filter on Device and overclock to 1000

![image_2024-07-21_191846601](https://github.com/user-attachments/assets/b10a902e-9a3c-46a7-a7a6-1061739fd8a3)

**Comment by LordOfMice** [comment]
1. You have to read pinned issues. 
2. You got some message when try to overclock but ignore it.
