### ISSUE TITLE
Overclock won't actually do it in game

### ISSUE THREAD

**Issue by Claymorerl** [LordOfMice/hidusbf#315]
Basically I open the program and have the rate at 8k, I open said game and I notice that the overclock isn't actually registering like it was the night previous when I installed it, unplugged controller plugged back in, restarted program, closed program and reopened, gonna try in uninstall and reinstall but having to do that every time to fix the issue seems a bit much, im sure im missing something but not sure what, fyi this is a ps5 controller im overclocking and the wire goes directly on top of my pc

**Comment by LordOfMice** [comment]
1. Wiki: Overclocking suddenly stops after a while
2. https://github.com/LordOfMice/hidusbf/issues/311
