### ISSUE TITLE
Why can some devices be underclocked but not overclocked?

### ISSUE THREAD

**Issue by itsgrimetime** [LordOfMice/hidusbf#318]
Sorry for using issues to just ask a generic question, but I'm having a hard time finding this information:

I have a USB controller adapter (for nintendo gamecube controllers) that can be successfully underclocked, but not overclocked (it won't go above 125hz). From my understanding the device is quite simple, and very similar to other devices that can be overclocked. Is the ability to underclock but not overclock a limitation of the USB-device chip in use in the device, or something related purely to software/the driver? Unfortunately the actual IC is unlabeled in the device so I can't find specifications on internal clockrate/etc if there are any.

Also, the readme states:
> If the rate does not increase more than 125Hz, then you should try DECREASE it to 31Hz or 62Hz. If the rate does decrease, then the driver functions properly, however or you mouse is not overclockable; or USBPORT.SYS/USBXHCI.SYS was altered or simply too new and so unknown to the program.

Is there any way for me to be able to tell which case applies for this device?

**Comment by LordOfMice** [comment]
>Is the ability to underclock but not overclock a limitation of the USB-device chip in use in the device, or something related purely to software/the driver?
>Is there any way for me to be able to tell which case applies for this device?

If you can overclock other (well-known overclockable, i.e. reference) Low Speed device over 125 Hz on your system then the limit is your device (hardware or firmware). And this is described in manual.

>Why can some devices be underclocked but not overclocked?

And the answer this question is obvious - underclocking in general (not only USB devices case) is much simpler than overclocking.
