### ISSUE TITLE
When controller overclocked my fps drops significantly

### ISSUE THREAD

**Issue by synoelo** [LordOfMice/hidusbf#319]
when i oveclock my playstation 5 controller to 8000 my fps drops form 180 to arround 120 when i play fortnite i tryed reseting my pc and this did not help. do you have any idea how i can fix this, thanks

**Comment by LordOfMice** [comment]
i assume you have to read something.
wiki: Game Input Engines and high polling rates: https://github.com/LordOfMice/hidusbf/issues/311
