### ISSUE TITLE
issue when i filter on device 

### ISSUE THREAD

**Issue by slaiza** [LordOfMice/hidusbf#320]
![Captura de pantalla (2)](https://github.com/user-attachments/assets/89200474-a579-440d-b871-f3eaba3b98fe)
i turn off windows defender
i turn off secure boot inn bios 
and at bottom left says in english: that a security config prevents the download of this driver. you must have to set a config for downloading

**Comment by LordOfMice** [comment]
PINNED Issue https://github.com/LordOfMice/hidusbf/issues/54
