### ISSUE TITLE
OC not registering

### ISSUE THREAD

**Issue by keepitlive** [LordOfMice/hidusbf#322]
So ive used the oc software a couple of times now and i just got a new pc and oc my controller with no issues but in game it still feels delayed and i know how an oc controller feels and it doesnt feel like this , any solution to this issue?

**Comment by keepitlive** [comment]
![Error 9_17_2024 6_41_23 PM](https://github.com/user-attachments/assets/61c7e890-3f13-41cf-996e-26c8727d647e)

**Comment by LordOfMice** [comment]
1. I can not help with "feeling".
2. https://github.com/LordOfMice/hidusbf/issues/301

**Comment by keepitlive** [comment]
does this look like that was my issue ? 
are u slow?
