### ISSUE TITLE
Hidusbf safe? 

### ISSUE THREAD

**Issue by Spikes6** [LordOfMice/hidusbf#323]
Is Hidusbf Programm safe for my Pc and how i make it with secure boot on because some game need to be on can i get the Support for that he know evrything abot that?

**Comment by LordOfMice** [comment]
I assume you have to read readme.

**Comment by Spikes6** [comment]
Just because it's in there doesn't mean it's immediately secure. Also, why isn't the certificate trustworthy?

**Comment by Spikes6** [comment]
Are there any damages if you do it, disadvantages if you do it wrong and if you want to do secure boot with which regist key should you use the UpgradedSystem or WqhlSettings?

**Comment by Spikes6** [comment]
and what is the difference between the two reg keys and what do they do?

**Comment by LordOfMice** [comment]
>and what is the difference between the two reg keys and what do they do?
I assume you have to reread THE CURRENT readme. There is described the current restrictions and they are not the Scure Boot related.

**Comment by Spikes6** [comment]
does it have a video tutorial about that?

**Comment by LordOfMice** [comment]
The most recent manual is:
https://battlebeavercustoms.com/pages/overclocking
And you can get enough video manuals just googling "hidusbf". But pay attention that something might have changed since.
