### ISSUE TITLE
My setup desappears when i click install service

### ISSUE THREAD

**Issue by Fr1kk** [LordOfMice/hidusbf#325]
Hey! im not a tech guy and im having this issue

I did all the steps and open the steup, whe click install service this erros shows up “Error trying to test loading of filter service: 2 “the system cannot find the file specified” something (windows 10+ x64 with secure boot, antivirus, protection/anticheat engine, broken installation of service, absent or wrong
C:\windows\system32\drivers\hidusbf.sys, hidusbf.sys from hidusbfN.zip without test mode on x64, enforced kernel code loading policy, enable memory integrity, etc.) prevents filter service fr running; device will stop functioning after [Restart] with high probability, continue Setup? what should i do?

**Comment by LordOfMice** [comment]
> whe click install service this erros shows up “Error trying to test loading of filter service: 2

I assume your erroneously described behaviour of this software as you can NOT get such message when you are installiing HIDUSBF service by pressing [Install Service] button.
