### ISSUE TITLE
mouse bInterval returning to default every restart/replug, polling rate also returns to default as per polling rate test

### ISSUE THREAD

**Issue by ReyesJayMilson** [LordOfMice/hidusbf#327]
1k polling rate works and all is fine except it resets every time I restart or unplug then replug the mouse. also default mouse has a bInterval of 10 but when it goes to 1 when its installed

**Comment by LordOfMice** [comment]
bInterval to Defaultl only or Filter? to No too?

**Comment by ReyesJayMilson** [comment]
![image](https://github.com/user-attachments/assets/6bdbb530-82d2-4fad-9d59-19f742c1ee43)
Here is the default

![image](https://github.com/user-attachments/assets/36103721-397e-41af-8020-6129463300e3)
Here is when its installed, filter on, 1000hz then clicked restart

![image](https://github.com/user-attachments/assets/28cd615c-c132-458f-9548-b69981cce1ac)
Here is after uninstall service and unticked filter on but havent restarted yet

![image](https://github.com/user-attachments/assets/6cdcf719-f878-4d44-936f-9d29c6225422)
Here is after i click restart

**Comment by LordOfMice** [comment]
>Here is after uninstall service and unticked filter on

And what are you waiting for after this? Overclocking still?
