### ISSUE TITLE
Won't Work

### ISSUE THREAD

**Issue by FormidibleThunder** [LordOfMice/hidusbf#328]
I've tried all forms of troubleshooting and it still doesn't work. I tried everything from disabling secure boot, installing the SweetLow certificate and doing both UpgradedSystem and Whql registry tweaks to no avail. I'm on Windows 11 Enterprise and trying to overclock a 8bitdo Ultimate controller. 

The error I get is 
![Screenshot 2024-10-05 134931](https://github.com/user-attachments/assets/9f4ed1f7-671c-40ca-a1c7-88c977b4efbc)

I'm having two thoughts on this

1: Maybe I just can't OC this controller
2: The process is very different between Home and Enterprise versions of Windows 11

**Comment by LordOfMice** [comment]
I assume that Access denied means that you tried to setup under User account. This software requered Admin rights.
