### ISSUE TITLE
still on 3.5ms delay after overclock

### ISSUE THREAD

**Issue by okekechuks** [LordOfMice/hidusbf#329]
Hi, i know this might be late but i have an issue where when i plug in my controller it is on 3.5ms delay, when i overclock it and check again it is still on 3.5ms. i had a ps4 controller it worked on, i got 2 more and they refuse to overclock
![Screenshot 2024-10-15 172519](https://github.com/user-attachments/assets/17be9916-447c-4836-8c2b-2c60fce58e1b)
![Screenshot 2024-10-15 172619](https://github.com/user-attachments/assets/661ee765-50de-480f-9f04-40be7f998a86)
![Screenshot 2024-10-15 172746](https://github.com/user-attachments/assets/acdb34d3-daae-499b-b478-ff0c9d9bbed6)
![Screenshot 2024-10-15 172831](https://github.com/user-attachments/assets/729bce2c-e2d9-4e40-a9f2-025aa51f3929)

**Comment by LordOfMice** [comment]
> i had a ps4 controller it worked on

On the SAME system? Then you just have unoverclockable devices.

**Comment by okekechuks** [comment]
yes my pc has an amd ryzen 5 7535HS, will that be an issue?

**Comment by LordOfMice** [comment]
You did not answer my question but asked your. Something went wrong.

**Comment by okekechuks** [comment]
oh sorry about that, i first overclocked with my old pc (cpu was i5-8300H), the controller went from 3.5 to 0.5, got a new pc and new controllers, tried the already overclocked controller on my new pc and its still 0.5ms delay, stopped using the controller because of stick drift and weak buttons.

**Comment by LordOfMice** [comment]
>tried the already overclocked controller on my new pc and its still 0.5ms delay

Ok, if some device is overclockable on some system and other device is not on the same system then problem with high probability is device, not the system. But! - do not forget about using USB hubs too.
In any case the better is to test overclocking of your new controllers on some other system (your old PC may be?), of course.

**Comment by okekechuks** [comment]
what do you mean by using USB hubs?, also i just uninstalled all HIDUSBF.INF and reset the overclock status back to default. I want to restart the process.

**Comment by okekechuks** [comment]
just did it again, i'll check if it worked
![image](https://github.com/user-attachments/assets/4b776ba8-7f8d-45b8-9416-26e8f9147210)

**Comment by okekechuks** [comment]
did not work
