### ISSUE TITLE
eveytime i install the sverice with filter on the device gets driver error from my pc but i have tried it on a laptop and it worked 

### ISSUE THREAD

**Issue by mahfoodh-nlip** [LordOfMice/hidusbf#332]
![Screenshot 2024-11-12 182352](https://github.com/user-attachments/assets/b42b553b-277f-4d80-8968-874c02316103)
hello i need help eveytime i install fliter on i get driver error

**Comment by LordOfMice** [comment]
"error" is not descriptive
