### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by ExoKiru** [LordOfMice/hidusbf#333]
i been trying to fix this for 3-5 hours already i just want to play my game but, i recently reinstalled windows on my pc and tried to overclock it again, i tried everything on the youtube videos and nothing happened
![Screenshot 2024-11-15 150709](https://github.com/user-attachments/assets/83dc6ab9-c35b-43f2-9539-2d8424792f1a)

**Comment by MrDJ93** [comment]
ive got the same issue.

**Comment by ExoKiru** [comment]
> ive got the same issue.

I can help you add me on discord exokiru i fixed it

**Comment by LordOfMice** [comment]
It is HIDUSBF.SYS file not copied to %windir%\system32\drivers (probably caused by partially not working install script) or locked there by AV.

>on discord exokiru i fixed it

I assume it is better to share you expirience here, i can reference it.
