### ISSUE TITLE
same issue as before it was never solved but it was closed regardless "setup.exe is deleting itself"

### ISSUE THREAD

**Issue by oskarjhk** [LordOfMice/hidusbf#34]
if you want details look at the already closed issue. I have no antivirus I even went as far as to turn off windows security temporarily and that didn't work. Also, it is interesting to note that when I pressed install service this window (below) showed up for one frame.
![image](https://user-images.githubusercontent.com/68066983/105368979-fc21f400-5bf9-11eb-88d2-2191293660f7.png)

Edit: I can find the system file in my system 32 folder but the issue is still here

**Comment by LordOfMice** [comment]
>I have no antivirus
>>Check your AV or **something like this.**

It may be software protection or game anti-cheat engines (they like to prevent some activity). But once again - it is your system problem. And just hint for you - on NTFS file deletion can be traced to responsible process through auditing, i suppose.
