### ISSUE TITLE
Overclocking Controller isn't working.

### ISSUE THREAD

**Issue by retrowtf** [LordOfMice/hidusbf#35]
So, I tried overclocking my controller, and it pops up with an error that looks like this: 
![image](https://user-images.githubusercontent.com/77965154/105692909-ef9de400-5ef6-11eb-9ec3-a33e5c9a7f2b.png)
Does anyone know how to fix this?

**Comment by retrowtf** [comment]
![image](https://user-images.githubusercontent.com/77965154/105693059-2aa01780-5ef7-11eb-9475-e691ea1552fa.png)
then it shows up like this.

**Comment by LordOfMice** [comment]
Yes.
