### ISSUE TITLE
Windows 10 x64 Without forcing unsigned drivers

### ISSUE THREAD

**Issue by Jos158v** [LordOfMice/hidusbf#36]
There is a way to overclock my mouse and keyboard without forcing unsigned drivers?
If i force unsigned drivers i can't play games protected by Anti Cheats like Apex Legends and Valorant...

**Comment by LordOfMice** [comment]
Depends on device you try to overclock. Drivers from hidusbf are signed and can run everywhere. Drivers and patches from hidusbfn are unsigned and need TestMode or atsiv to load.
