### ISSUE TITLE
filter error

### ISSUE THREAD

**Issue by zincwyd** [LordOfMice/hidusbf#37]
Whenever i press filter on device it gives me a error
![error](https://user-images.githubusercontent.com/78324206/106399228-fa67e580-63dc-11eb-82e9-7f248554f58d.png)

**Comment by gtail880** [comment]
I have this same exact issue when trying to follow the steps for my DS4. I heard/read that disabling secure boot is the only option to fix this but I’m not sure. I also don’t even know how to do that or if it’s safe/effective.

**Comment by LordOfMice** [comment]
Try to read something before write, this is described in readme and pinned issue.
