### ISSUE TITLE
Driver should be signed by Microsoft to avoid security vulnerabilities

### ISSUE THREAD

**Issue by boulajp** [LordOfMice/hidusbf#39]
Windows will not allow for persistent installation of this driver, since it has not been signed by Microsoft. To circumvent this, Secure Boot must be disabled in order to use it. Disabling secure boot opens the door for malicious kernel-level software to be installed. 

Why not get this driver signed by Microsoft? That way, it could be used without creating security vulnerabilities. More information about how to submit drivers to be signed by Microsoft can be found here:

- [Create a New Hardware Submission](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/create-a-new-hardware-submission)
- [Signing a Driver for Public Release](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/signing-a-driver-for-public-release)

**Comment by LordOfMice** [comment]
If you try to read something before write you will find this:
https://github.com/LordOfMice/hidusbf/issues/16#issuecomment-707788749
And yes, I didn't see keywords "I have Verified Microsoft Account and ready to sign your driver" in you post.
