### ISSUE TITLE
My controller won’t Overclock

### ISSUE THREAD

**Issue by SSJGibby** [LordOfMice/hidusbf#40]
I have either an anti-cheat or anti-virus that won’t let me Overclock my controller. When I do it just disable the device. Is there a setting or something I need to switch? I’ve tried all that I know to try. Googled it a 100 times. Can’t seem TTK get it to work. Bar just turns red and I can’t use the controller anymore till I revert the changes made. Any help or advice I’d appreciated.

**Comment by LordOfMice** [comment]
I think Setup has to show some error code and description when you try to install filter on device. But you are omitted this information for unknown reason.

**Comment by SSJGibby** [comment]
I’m currently in bed and not at my pc so I didn’t know the error code. But
apparently it’s a problem with the secure boot cause someone has already
had the same issue before. It’s a thing with Asus motherboards apparently.

**Comment by LordOfMice** [comment]
>it’s a problem with the secure boot cause someone has already had the same issue before
why are you asking for help if you know the answer?

**Comment by SSJGibby** [comment]
I’m new to all of this and don’t know how to work whatever this forum is. I
posted them I saw later on that it was already talked about.

**Comment by handyprod** [comment]
![image](https://user-images.githubusercontent.com/93625254/139964567-a939ec8e-2a9c-4b1e-847e-1a3d3abc0435.png)
 hi , ive installed services i dosent show anything like if something really installed and dosnt show any error mesage neither , but my bi interval is still 5

**Comment by LordOfMice** [comment]
Restart...

**Comment by Seniic** [comment]
Can someone please help me?
I have windows 11 and GitHub to overclock my ps4 controller isn’t working 
It appears red bar and I can’t use the controller.
I have input delay around 1-1,5 and I want it to put to 0-0,5% 
What should I do?

**Comment by LordOfMice** [comment]
You should read readme (more i can say - WARNINGS in readme) and pinned issues.
