### ISSUE TITLE
hidusbf.inf won't install

### ISSUE THREAD

**Issue by Gingynator** [LordOfMice/hidusbf#42]
It's very odd. I've been using this program for about 6 months when I replaced my controller. My new controller behaved erratically with EDIT: *a small portion of* inputs that would come in half a second late (typical for a ds4 on bluetooth connection) so I uninstalled hidusbf for a fresh reinstall. The issue is now when I run setup.exe and I click "Install Service" I get an error message that simply says "Installation Failed". I get the same issue when I try to manually install HIDUSBF through right click -> Install. Any help would be appreciated.

Edit: Windows 10 OS. Verified all updates are installed and Geforce Experience verified all drivers are up to date.

**Comment by LordOfMice** [comment]
if you will execute this command with admin rights:
sc create hidusbf type= kernel start= demand binpath= system32\Drivers\hidusbf.sys
(spaces ARE matter) and copy appropriate hidusbf.sys (from amd64 folder, probably) to %windir%\system32\Drivers\
then you get exactly what installation of hidusbf.inf does.

**Comment by Gingynator** [comment]
I verified that my account has admin rights (which it would since it's the only user) and it still wouldn't work. I copied and pasted your command in the command prompt. 
![hidusbhelp](https://user-images.githubusercontent.com/5865465/107408190-a0e87080-6ad8-11eb-9793-f4d82b006ff9.PNG)

**Comment by Gingynator** [comment]
The hidusbf.sys file is already in there, along with another one from 2019. Should I delete those and replace them?
![hidusbhelp2](https://user-images.githubusercontent.com/5865465/107408932-9bd7f100-6ad9-11eb-8221-e9c15b2ad571.PNG)

**Comment by Gingynator** [comment]
I learned that I can run the command prompt as an admin. Phew. I tried again and this is what I got:
![hidusbhelp3](https://user-images.githubusercontent.com/5865465/107409523-47814100-6ada-11eb-8730-c37b9f3d3573.PNG)

**Comment by LordOfMice** [comment]
>The hidusbf.sys file is already in there, along with another one from 2019. Should I delete those and replace them?
There is only ONE hidusbF.sys. "another one from 2019" is system file and its name is NOT hidusbF.sys.

>I tried again and this is what I got
ok. reboot. you install hidusbfU.inf - this is file to DELETE service. After that try to install hidusbf service by usual way through setup->[Install Service]. Be careful - one letter difference is MATTER.

**Comment by Gingynator** [comment]
I deleted the hidusbf.inf and it's working now as indicated by the filter -> yes, rate - > 1000 (what I want), and bit interval - > 1. I don't know if this is something interesting that will help you in the future, but I still got the error message with "install service", but it works now so I'm not complaining.

**Comment by Gingynator** [comment]
Also I really appreciate all of your help :)

**Comment by alighasoub-web** [comment]
> if you will execute this command with admin rights: sc create hidusbf type= kernel start= demand binpath= system32\Drivers\hidusbf.sys (spaces ARE matter) and copy appropriate hidusbf.sys (from amd64 folder, probably) to %windir%\system32\Drivers then you get exactly what installation of hidusbf.inf does.

I just created this account to just thank you so much because of this command , my overclocking worked i tried all options and this one that worked for me . I had the 1060 error
