### ISSUE TITLE
controller driver error 

### ISSUE THREAD

**Issue by kingofvisuals** [LordOfMice/hidusbf#44]
Hey whatsupp,

So a couple of days I was trying to overclock my controller to play call of duty warzone its a ds4. After clicking a few buttons and stuff my controller stopped reacting. It's been a couple of days since I tried fixing ther drivers but nothing seems to be working. Windows does recognize the controller but it does not have any input in any game. Could someone please help me with this issue.
with kind regards.

**Comment by LordOfMice** [comment]
If you have problem when use this software then just disable it on such device. If you have  problem after that step then you have hardware problem and asking help in wrong place.
