### ISSUE TITLE
is there ways to have custom rate?

### ISSUE THREAD

**Issue by huizichin** [LordOfMice/hidusbf#45]
is there ways to have custom rate?
like 800 instead of 1000 just having an option to keying your own rate

**Comment by LordOfMice** [comment]
no, only predefined rates (used in setup.exe, JFYI)

**Comment by huizichin** [comment]
is there any chances of adding this feature?

**Comment by LordOfMice** [comment]
No, this is hardware and software restriction of USB host controllers.
