### ISSUE TITLE
No binterval is it even working?

### ISSUE THREAD

**Issue by isam567** [LordOfMice/hidusbf#46]
I'm using an Xbox One controller with a wireless adapter but when I overclock the adapter it says no binterval and I have noticed no changes in the delay so I'm not sure what to do. I reinstalled my adapter drivers trying uninstalling the program and it doesn't reset.
![image](https://user-images.githubusercontent.com/79573073/108981384-986d6980-7684-11eb-8ab2-ee99f0081370.png)

**Comment by LordOfMice** [comment]
This software is useless for devices without some hardware properties (i.е.  Interrupt Endpoints) and Setup warns when you try to set filter on such device.
