### ISSUE TITLE
Readme clarification?

### ISSUE THREAD

**Issue by Kein** [LordOfMice/hidusbf#48]
>This driver/program is intended to "overclock" USB mice **(and other devices)** 

>Program changes **only mouse rate**, not touching other devices on USB.

???

**Comment by LordOfMice** [comment]
Check is it correct now.

**Comment by Kein** [comment]
What happens if a device already has vendor drivers installed?

**Comment by LordOfMice** [comment]
There is no difference MS or vendor drivers used.

**Comment by Calzzy** [comment]
Sir how do i fix this
when i type Atsiv.exe -f hidusbf.sys and enter this shows up
0xc0000001, failed to load Atsiv service

**Comment by LordOfMice** [comment]
It's offtopic for this issue.
But you have to 
1. run atsiv with elevated privileges, of course 
2. carefully read info from link to OCN. In addition to antiviruses some game protection engines prevent atsiv driver loading. And there is workaround for some (not all) cases.
