### ISSUE TITLE
Error when trying to overclock my ps4 controller

### ISSUE THREAD

**Issue by app4k** [LordOfMice/hidusbf#49]
When I click "install service" I get the two warnings attached below. Any ideas on how to fix this?
![Setup_oqKgljNRLs](https://user-images.githubusercontent.com/80354439/110520135-b2229e00-80d3-11eb-9d92-c30438ec55ad.png)
![Setup_a5mN2hMga7](https://user-images.githubusercontent.com/80354439/110520144-b484f800-80d3-11eb-9c12-ce40a8b121c0.png)

**Comment by LordOfMice** [comment]
When you [Install Service] you can not get these messages. You will get this messages on [Filter On Device] exactly if you didn't Install Service first.

>Any ideas on how to fix this?
read readme, of course

**Comment by LordOfMice** [comment]
readme:
In case of HIDUSBF service wasn't installed through SETUP.EXE (button "Install Service") you may try to do this by OS standard possibility: mouse right button click on HIDUSBF.INF -> Install
And, of course, unzip all package before anything else.
