### ISSUE TITLE
Windows 10 version 1909 support?

### ISSUE THREAD

**Issue by Ulexos** [LordOfMice/hidusbf#5]
Is 1909 supported/going to be supported anytime soon if it is not yet? I am on 1909 and the overclock does not want to apply, underclocking to 62hz works, but the program freezes whenever i click on "install service" or "restart".

Am on Windows 10 Education N 1909 with all the latest updates installed as of writing this (optional updates are not installed, except for the Media Feature Pack) on an AMD Ryzen Zen+ 2600x build.

**Comment by LordOfMice** [comment]
1909 is equal to 1903. To learn more look at the link in readme.md (the last p.s. there)
>underclocking to 62hz works, but the program freezes whenever i click on "install service" or "restart".
It's mutually exclusive. Either underclocking is working, or it freezes.
