### ISSUE TITLE
Support other USB HID devices (keyboards, controllers)

### ISSUE THREAD

**Issue by mat1jaczyyy** [LordOfMice/hidusbf#52]
Does this driver support USB keyboards and USB game controllers? In particular, I have a Logitech K120, a Roccat Suora and an Xbox 360 Guitar Hero X-plorer that I'd like to hard overclock.

There's a legitimate use to having such a high polling rate, in Guitar Hero we are very often hitting multiple keys by bending our wrist so the angle decides which keys are pressed first, as well as sliding on our keys with multiple fingers at once at times. The extra resolution is actually extremely important.

Asking because readme explicitly says it changes USB mouse rate, not touching other devices, so I'm not sure whether it actually applies any changes to other kinds of devices.

**Comment by LordOfMice** [comment]
This driver supports any device with Interrupt Endpoints. Green lines in Setup.

>Asking because readme explicitly says it changes USB mouse rate, not touching other devices
You read previous version. Check readme.md of this project.

**Comment by mat1jaczyyy** [comment]
Thank you!
