### ISSUE TITLE
Failed to install service

### ISSUE THREAD

**Issue by TheRealGeDev** [LordOfMice/hidusbf#53]
![Capture d’écran (1)](https://user-images.githubusercontent.com/61166703/111902835-99a17480-8a3f-11eb-805b-18edd378c1b0.png)
can't install the service for some reason. 
win10 1909 / no antivirus / secure boot off / no virus of some sort / no anticheat

btw using this version https://www.youtube.com/watch?v=DtY_3sAJJnE the service installs but the device manager says that it's corrupted / the reg key is fucked up

**Comment by LordOfMice** [comment]
577  means secure boot on with version from hidusbf.zip or you try to use version for test mode (from hidusbfn.zip) under non test mode

**Comment by TheRealGeDev** [comment]
secure boot is off and i m not using the test mode one

**Comment by LordOfMice** [comment]
So answer is simple - you can't get this error if you have ordinary system. Of course, I know how to get this error on system without Secure Boot and (with high probabylity) how to load my driver on system with Secure Boot - but this is not _ordinary_ knowledge.
