### ISSUE TITLE
Cannot install service

### ISSUE THREAD

**Issue by samh1ll** [LordOfMice/hidusbf#56]
I cannot install service on my controller, or any device. I click install service and it simply opens and quickly closes a window, doing nothing. I am on Windows 10 and given the prompt to allow changes when opening setup.exe

**Comment by LordOfMice** [comment]
>doing nothing

Why do you think so? Did you try the next step?

**Comment by samh1ll** [comment]
Next step? i have deactivated secure boot etc.

**Comment by LordOfMice** [comment]
Yes, the next step, exactly as in readme:

>Then choose the line with your mouse and put a checkmark Filter On Device.

**Comment by samh1ll** [comment]
I have done my best to do all steps in the readme. I have no way to check with my controller on Mouse Rate Checker but i did the same steps on my mouse to test and the rate hasnt changed

**Comment by LordOfMice** [comment]
>the rate hasnt changed
>all steps in the readme
Not all, of course.

**Comment by samh1ll** [comment]
Well evidently yes but i am clearly unable to see where

**Comment by LordOfMice** [comment]
Because you are thinking that there is unimportant parts. There is NOT. Try to decrease rate as readme recommends.

**Comment by samh1ll** [comment]
I have tried doing the install with the .INF file also and a pop up appears and instantly dissapears also

**Comment by samh1ll** [comment]
OK i can go down on my mouse

**Comment by samh1ll** [comment]
but i am unsure how to know if i can on my controller
