### ISSUE TITLE
is it working?

### ISSUE THREAD

**Issue by Acealized** [LordOfMice/hidusbf#58]
is it working if it is red and has no bInterval
"USB\VID_045E&PID_02EA\3032363030303536303635373435"
"USB\VID_045E&PID_02EA&REV_0301"
"USB\VID_045E&PID_02EA"
  Name: Xbox One Controller
  Driver: dc1-controller
  Binary: \SystemRoot\System32\drivers\dc1-controller.sys
    Path: C:\WINDOWS\System32\drivers\dc1-controller.sys
    Version: 1.0.0.1 (WinBuild.160101.0800)
  Binary: HIDUSBF.SYS
    Path: C:\WINDOWS\System32\DRIVERS\HIDUSBF.SYS
    Version: 1.2.0.0
  LowerFilters: hidusbf
  BusSpeed: 1
  Overrided.bInterval: 1

Controller:
"PCI\VEN_8086&DEV_A12F&SUBSYS_82F1103C&REV_31\3&11583659&1&A0"
"PCI\VEN_8086&DEV_A12F&SUBSYS_82F1103C&REV_31"
"PCI\VEN_8086&DEV_A12F&SUBSYS_82F1103C"
"PCI\VEN_8086&DEV_A12F&CC_0C0330"
"PCI\VEN_8086&DEV_A12F&CC_0C03"
  Name: USB xHCI Compliant Host Controller - Intel(R) USB 3.0 eXtensible Host Controller - 1.0 (Microsoft)
  Driver: USBXHCI
  Binary: \SystemRoot\System32\drivers\USBXHCI.SYS
    Path: C:\WINDOWS\System32\drivers\USBXHCI.SYS
    Version: 10.0.19041.662 (WinBuild.160101.0800)

**Comment by LordOfMice** [comment]
I assume if is red you got some message when setup - with error description. So you have to read readme and pinned issues.
