### ISSUE TITLE
HidUSBf Not Doing anything

### ISSUE THREAD

**Issue by TicianoBLTO** [LordOfMice/hidusbf#60]
Hello when i try to overclock the polling rate donsen't change in any device i have test mode activated,and with dseo i sing the drives but nothing any help??

**Comment by TicianoBLTO** [comment]
I Have Win10 Pro MiniOS v19041.vb
and the mouse is Noganet ST-002

**Comment by TicianoBLTO** [comment]
i desisntalled all usb drivers too

**Comment by LordOfMice** [comment]
1. Before overclock try to underclock. I did not see any reaction to https://github.com/LordOfMice/hidusbf/issues/59
2. If you can not overclock but can underclock -  read readme once again. There IS link.
