### ISSUE TITLE
Over clock fail

### ISSUE THREAD

**Issue by turkeybagger** [LordOfMice/hidusbf#62]
Tried to over clock my C 40 remote.  Went through the steps and everything looked good with the exception of the binterval saying 1-16.  I don’t remember if I unplugged my remote after another “install service” but now I see the device name but the bar is red and binterval has no # in it.  My remote isn’t being recognized w the Astro software and I can’t figure out how to get remote back working.

**Comment by LordOfMice** [comment]
I think you have to read something. Especially when you have some problem.
