### ISSUE TITLE
I overclock my controller but it doesn’t feel overclock it feels the same as before need help please 

### ISSUE THREAD

**Issue by Yaviel** [LordOfMice/hidusbf#65]
Hello, I’ve been dealing with controller delay for a year now I’ve tried to overclock my controller and it says it’s at 1ms but it doesn’t feel like 1ms it feels like the same as before and I don’t get no error.

**Comment by LordOfMice** [comment]
Once again, here we discuss problems with this software, not feelings. And this is overclocking, nobody can guarantee something successful.
