### ISSUE TITLE
Help with PS5 DualSense overclocking

### ISSUE THREAD

**Issue by UzyFF7** [LordOfMice/hidusbf#68]
Hi, 

I've successfully downloaded the program and overclocked my controller, however I'm not sure if the overclock has actually worked. I say this because when I overclocked my mouse, I was able to underclock it, so when I changed it to rate 31, my mouse felt super slow, and when i went to 1000 it was fast and responsive, which I can safely conclude the overclock has worked. 

However, in the case of the DualSense controller, when I went to 31 rate it felt exactly the same as when I went on a 1000 (the input delay felt normal, same as a console I would say). Also since DualSense doesn't have official Sony drivers right now, you have to run it with ds4 and within ds4 you can see the input delay. I will attach pictures for both 1000 and 31 rate, and tell me if having rates of 0ms and 3,5ms with the respective rates are normal or if I'm doing something wrong. 

Thanks in advance.

![1](https://user-images.githubusercontent.com/84816933/119578055-b77ab500-bdb3-11eb-90ea-dac6b04154e0.png)
![2](https://user-images.githubusercontent.com/84816933/119578066-b9dd0f00-bdb3-11eb-87dd-f16d251b0571.png)

**Comment by LordOfMice** [comment]
bInterval is changed to 1 -> if this device is Full Speed (probably it is as any modern HID devices except the cheapest mice and keyboard, but easy check by [Copy IDs]) then overclocking is successful. As something external (delay in this case) is changed too it is definitely successful. But
1. You didn't check default (nor over- nor under- clocking) behaviour.
2. "felt" is completely wrong term in this particular area. I am not psychologist.
