### ISSUE TITLE
Overclocking Xbox series controller

### ISSUE THREAD

**Issue by Lizer58** [LordOfMice/hidusbf#69]
Hi, after fixing the error 577 of secure boot, i tried to overclock my xbox series s/x controller. After doing everything, my controller doesn't work. The funny fact is that with ds4 this doesn't happen
![Screenshot_31](https://user-images.githubusercontent.com/84973028/119983677-c1253800-bfc0-11eb-9354-3493c88c6f43.png)

**Comment by LordOfMice** [comment]
The answer is very simple - try to lower rate. It's OVERclocking, no one can guarantee anything.
