### ISSUE TITLE
Device will stop funcioning after restart? Error Trying to test loading of filter services: 577

### ISSUE THREAD

**Issue by nucshi** [LordOfMice/hidusbf#71]
When trying to overclock my PS4 controller, it gives me an error 577 code. Now my controller shows up as RED on the list. I just want to make sure that this didn't damage my computer or controller in some way. My real question is what does it mean by "device will stop functioning after restart"?

I attached some screenshots to show what I mean.

![Screenshot (8)](https://user-images.githubusercontent.com/85324083/120732717-c1876c80-c4b3-11eb-90e6-881532df2278.png)
![Screenshot (9)](https://user-images.githubusercontent.com/85324083/120732722-c4825d00-c4b3-11eb-99b9-05e95bafab02.png)

**Comment by LordOfMice** [comment]
>error 577 code

It's time to read something.

>what does it mean by "device will stop functioning after restart"?

Literally this. Will not work.
