### ISSUE TITLE
Disable secure boot dosnt work

### ISSUE THREAD

**Issue by Gremlin-Toss** [LordOfMice/hidusbf#72]
hey all im use the tuf gaming x570-plus (wi-fi) and it us unable to disable secure boot dose anyone know how i can run this without disabling it ?

**Comment by LordOfMice** [comment]
Of course, someone know. I think definitely the author of readme of this software.

**Comment by LordOfMice** [comment]
This is the third question without any reaction. Strong correlation between shitty hardware and its users...
