### ISSUE TITLE
non test mode drivers don't work for me on 1909 and 21h1

### ISSUE THREAD

**Issue by FischerandomONLY** [LordOfMice/hidusbf#73]
the only drivers that work for me on 21h1 and 1909 are the hidusbfn test mode drivers, do you know anything about this almighty lord of mice?

**Comment by LordOfMice** [comment]
Yes, I know. For non Test Mode you have to read about patcher (hidusbfp.sys from hidusbfn) and how to load it.

**Comment by FischerandomONLY** [comment]
thank you my lord, is there a tutorial for this?

**Comment by LordOfMice** [comment]
Of course. I can say 6 (or more) manuals. Follow the link to overclock.net from readme.
