### ISSUE TITLE
Error tying to test loading of filter service: 1060

### ISSUE THREAD

**Issue by stevieeejay** [LordOfMice/hidusbf#74]
The specified service does not exist as an installed service. 

I see exact issue in previous threads, but I don't understand your solution. "Install as a readme recommends. What does that mean actually?

**Comment by LordOfMice** [comment]
1. reboot
2. [Install Service] from setup or Right click on hidusbf.inf -> Install in Explorer EXACTLY as readme recommends.
3. to verify that service really created execute:
sc query hidusbf
from command console
You will have something like this:

SERVICE_NAME: hidusbf
        TYPE               : 1  KERNEL_DRIVER  
        STATE              : 4  RUNNING 
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
