### ISSUE TITLE
error when restarting

### ISSUE THREAD

**Issue by spiderman11786RL** [LordOfMice/hidusbf#77]
When i click restart it says
error!!!
'device doesnt restart after 10 seconds you probably have some problem in your system like running Setup without admin rights or you run Setup with current folder without Helper module (SX64.EXE) on x64 system or AV is preventing executing of Helper module or something or somethign holds this device opened. You can try to disconnect and then reconnect device or reboot system'.
The reason im putting this on here, is because i think it is causing the overclock not to work how do i fix this?

**Comment by LordOfMice** [comment]
>how do i fix this?

literally as software suggested you

**Comment by spiderman11786RL** [comment]
> > how do i fix this?
> 
> literally as software suggested you

but i do not know how to and what to do

**Comment by spiderman11786RL** [comment]
what is av

**Comment by LordOfMice** [comment]
>but i do not know how to and what to do

>>You can try to disconnect and then reconnect device or reboot system.

I assume you understand English and some simple terms.
