### ISSUE TITLE
Hello team Github Please Help me

### ISSUE THREAD

**Issue by Omar-Assassin-96** [LordOfMice/hidusbf#79]
Yes my brothers and sisters please help me out i want to make my ps5 controller 0ms to play on pc i tried but it keep giving me this messages i will upload the picture please i really want to play destiny 2 on my pc with 0ms or is there any new file i need to download that have all the drivers or something?

thanks in advance
![omar2222](https://user-images.githubusercontent.com/87354528/125396914-cd821a80-e3df-11eb-8625-9c1417173478.png)

**Comment by LordOfMice** [comment]
I think you have to read something like readme or pinned issue, eh?

**Comment by Omar-Assassin-96** [comment]
Hello my friend okay let me try
