### ISSUE TITLE
Controller OC Ghost Input

### ISSUE THREAD

**Issue by DrGGCoolman** [LordOfMice/hidusbf#8]
Hi,
I'm having issues with ghost inputs with the DS4 Controller after changing the polling rate to 1000Hz and 500Hz. E.g. if I drive forward in Rocket League the car randomly steers to the left. It seems to be related to the changes in polling rate, because reverting to default fixes the issue.

 I'm not sure if there is something that can be done about this, or it just might be an hardware issue on  my side, but I just assumed this might be the place to open up a discussion.

**Comment by fragtion** [comment]
Sounds like an issue with the DS4 controller to be fair. If hidusbf succeeds in making the port higher Hz then it's achieving it's purpose and the DS4 controller is discovered incompatible. Issue should be queried with their support rather. Just My 2c worth
