### ISSUE TITLE
Help! Controller twitching when installed service!

### ISSUE THREAD

**Issue by flygrizzle** [LordOfMice/hidusbf#80]
Hi my guy,

First and foremost, thanka for putting time and effort in the program, it has helped controller players on PC tremendously!

now my problem: i have had the service installed and working for about half a year now. I recently got a new controller, and installed the service again, and now my controller is twitching in game. I play only Cold War. 

Uninstalling filter and unlinking driver doesn’t help, and also i really want to use the service as playing with input delay vs no input is well, easy choice. 

I hope you can help me with the problem!

kind regards

**Comment by LordOfMice** [comment]
>Uninstalling filter and unlinking driver doesn’t help

I assume the answer is obvious - this is some kind of hardware problem.
