### ISSUE TITLE
Error 577 when trying to "filter on device" IMPORTANT!

### ISSUE THREAD

**Issue by NishanSing** [LordOfMice/hidusbf#81]
Hey @LordOfMice i know many people have been questioning "how do we fix error:577" and i can guess it must be annyoing. But us gamers we need a fix and we can't find one anywhere on the internet. Some of us cant use secure boot because when we disable secure boot we cant run fortnite. Is there any fix for this and can we atleast know what causes this issue. One last question will there be a new version of hidusbf coming out?

This is when we overclock our controllers!
![Capture](https://user-images.githubusercontent.com/77081940/126340607-4134388a-e5ac-4d99-b8a1-3cd3505c4f44.PNG)

**Comment by LordOfMice** [comment]
https://github.com/LordOfMice/hidusbf/issues/16#issuecomment-883918974
