### ISSUE TITLE
my controller stop working , please help me

### ISSUE THREAD

**Issue by onehitmc7** [LordOfMice/hidusbf#86]
i play with my ps4 controller with bluetooth paired with DS4 windows, i downloaded the program with the intructions from youtube and now when i cant edit the controller in your program and the games dont  get the controller inputs, while ds4 does, please help me bro, im very frustated :(

**Comment by LordOfMice** [comment]
If controller is working in one place and isn't working in other then it is not hidusbf related problem. And i can not help with third party software.
