### ISSUE TITLE
How to make it work on Windows 11?

### ISSUE THREAD

**Issue by Yuh777** [LordOfMice/hidusbf#88]
Hey, currently on the Windows 11 Beta rn and they force secure boot so I was wondering what I can do about driver not being installed. Ik you can install Windows 11 without secure boot right now but I feel that they will patch it in the future. In that case what can I do? The most successful thing I've down is disable driver enforcment from the troubleshoot menu, but it will only work till I restart/shut down my computer which I do every night.

**Comment by LordOfMice** [comment]
1. IDK. Windows 11 is Beta and i did't test it.
2. In any case:
https://github.com/LordOfMice/hidusbf/issues/16#issuecomment-883918974
