### ISSUE TITLE
PLS HELP !

### ISSUE THREAD

**Issue by skeptix34** [LordOfMice/hidusbf#89]
so i downloaded the software and tried to overclock and suddenly my controller color turned red ( on the software ) 
![Desktop Screenshot 2021 08 22 - 10 52 00 67 (2)](https://user-images.githubusercontent.com/89354747/130365028-7d9f6516-b0e3-4553-bc0f-ba9bc33c553c.png)

**Comment by LordOfMice** [comment]
1. You have to read readme.
2. >suddenly
There WAS warning.
