### ISSUE TITLE
pls fix your software 

### ISSUE THREAD

**Issue by skeptix34** [LordOfMice/hidusbf#90]
![Desktop Screenshot 2021 08 24 - 13 21 29 81](https://user-images.githubusercontent.com/89354747/130684510-912c4fd8-ef2a-4987-acc5-8c3b3f7310c5.png)

**Comment by skeptix34** [comment]
![Desktop Screenshot 2021 08 24 - 13 23 41 36](https://user-images.githubusercontent.com/89354747/130684870-07af2a6a-dc12-4550-ae28-9c9ef9ee0d0f.png)
what should i do ?!

**Comment by LordOfMice** [comment]
>what should i do ?!

I assume you have to read readme, of course, and unzip files BEFORE using in particular.
