### ISSUE TITLE
Getting "Error trying to test loading of filter service: 193"

### ISSUE THREAD

**Issue by dmg007** [LordOfMice/hidusbf#91]
I'm using hidusb to overclock my gcc, but I keep running into this error. I reset windows, disabled secure boot, and disabled driver signature and it still doesn't work. I haven't had this problem on the other computer I downloaded this on. 

![Capture](https://user-images.githubusercontent.com/89669890/131199600-500be167-4932-4bb9-a897-8e7bc0f8f5cf.PNG)

I'm pretty stumped and not sure of what else to do.

**Comment by dmg007** [comment]
Read up on the other issues, seems like it isn't related to your software specifically. Still not working, but I might try reinstalling windows again.

**Comment by LordOfMice** [comment]
>I might try reinstalling windows again

REinstalling may not help. If not then try clean install -> try hidusbf -> setup your usual software -> check that hidusbf is working still. And I am really interested to know what is the root of this problem.

**Comment by LordOfMice** [comment]
https://github.com/LordOfMice/hidusbf/issues/54
