### ISSUE TITLE
Further Help?

### ISSUE THREAD

**Issue by oskiin** [LordOfMice/hidusbf#93]
https://gyazo.com/a787f6cc580d8725c482d77a37d1bd41?token=e6b2c5916e8e2818d84c82c423479c16
Hi, i made a ticket before but it got instantly closed, is there a public discord we can join? 
Like said before, i Overclocked it before via the program and now it doesn't show up at all, i have considered Wiping my pc to resolve it. 

oskiin#1902

**Comment by LordOfMice** [comment]
I don't understand what is the problem you have.
All your devices definitely have Child names.
If device is not in list in Setup->All (or Setup->with Problem) then you have to find it in Device Manager (Device By Connection mode) and send screenshot - i can tell more after that. If device is NOT in Device Manager then it is just broken.

**Comment by oskiin** [comment]
https://gyazo.com/629e20e6948a203e201e7f5fd12f1889

**Comment by LordOfMice** [comment]
>Device By Connection
If you don't understand something you can NOT skip it. More i can say - this screenshot explained in manual.

**Comment by oskiin** [comment]
Yeah don't really understand mate ngl

**Comment by oskiin** [comment]
https://gyazo.com/e6428337ec94fc4ba36d729aa34cbfa1 i've filtered it by Device Connection in this screenshot, sorry about that

**Comment by LordOfMice** [comment]
Yes, this is By Device Connection mode but you did NOT read manual still. Where is the device you are trying to overclock and ANY USB device at all? Two screenshots of Device Manager from https://www.overclock.net/threads/usb-mouse-hard-overclocking-2000-hz.1589644/ look differently. Once again - if you did not understand something than you have to read ALL. And this is my last attempt explain you this fact.

**Comment by oskiin** [comment]
I had already over clocked my controller using the program but since then it stopped showing up in my Hidusbf, I will read the Manual and see what I can do, hasn’t been very straight forward for me. 
Im just trying to get low latency on my PS4 controller for Warzone etc.

**Comment by Perzapp** [comment]
Thx😀😀👍

Den fre 1 okt. 2021 11:36oskiin ***@***.***> skrev:

**Comment by oskiin** [comment]
@LordOfMice any possibllity of you being able to screenshare with me? also i do not have secure boot disabled is this a problem to?

**Comment by LordOfMice** [comment]
>>If device is not in list in Setup->All (or Setup->with Problem)

>also i do not have secure boot disabled is this a problem to?

Looks like you don't want to understand information at all.
