### ISSUE TITLE
Possible old version

### ISSUE THREAD

**Issue by Rectonic2** [LordOfMice/hidusbf#95]
I was curious as to why my hidusbf.sys file has the date modified of 2016, while another persons has the date modified of 2021. Its just a question if i am in fact using something wrong. A response would be great thankyou.

![Screenshot (14)](https://user-images.githubusercontent.com/91720620/135579425-24ef30f2-12a0-49f2-adca-39d4e2bf5679.png)

**Comment by Rectonic2** [comment]
I was also wondering if I should have anything running in services.msc as well.

**Comment by LordOfMice** [comment]
>my hidusbf.sys file has the date modified of 2016, while another persons has the date modified of 2021

Because this is really different builds from different packages and different models of using.

>I was also wondering if I should have anything running in services.msc as well.

I think it's time to RTFM. There is described what this software does in system and even HOW. The third P.S. from https://www.overclock.net/threads/usb-mouse-hard-overclocking-2000-hz.1589644/
